//! Cross-turn abstractive summary cache (#757).
//!
//! The compaction summarizer produces a summary of the "cold tail" of a
//! conversation. Within a single turn this is already cached (the local
//! `last_summary` variable). But across turns the cache was lost — each new
//! turn re-summarized from scratch even when only 1-2 messages were appended.
//!
//! This module provides a shared, per-session cache that survives across turns
//! so `run_turn` can seed its local state from the previous turn'\''s result.

use std::collections::HashMap;
use std::sync::Mutex;

use ff_core::Message;

/// Per-session cross-turn compaction summary cache.
///
/// Keyed by session_id. Thread-safe via interior `Mutex` — the lock is held
/// only for the duration of a HashMap get/insert (nanoseconds), never across
/// awaits. Only one `run_turn` per session runs at a time (enforced by the
/// cancel-before-spawn invariant upstream), so contention is effectively zero.
#[derive(Debug, Default)]
pub struct CompactionCache {
    inner: Mutex<HashMap<String, CachedSummary>>,
}

/// The cached summary state for one session.
#[derive(Debug, Clone)]
struct CachedSummary {
    /// Index into the wire at which this summary ends (exclusive). Messages
    /// `[0..boundary]` are covered by the summary; `[boundary..]` are verbatim.
    boundary: usize,
    /// The summary message itself (role=System or User depending on prompt).
    summary: Message,
    /// Transcript message count when the summary was produced. Used by
    /// `summary_due()` to decide whether the cache is stale.
    message_count: u64,
}

impl CompactionCache {
    pub fn new() -> Self {
        Self::default()
    }

    /// Retrieve the cached summary for a session, if any.
    pub fn get(&self, session_id: &str) -> Option<(usize, Message, u64)> {
        let guard = self.inner.lock().unwrap();
        guard
            .get(session_id)
            .map(|c| (c.boundary, c.summary.clone(), c.message_count))
    }

    /// Store (or overwrite) the summary for a session.
    pub fn put(&self, session_id: &str, boundary: usize, summary: Message, message_count: u64) {
        let mut guard = self.inner.lock().unwrap();
        guard.insert(
            session_id.to_owned(),
            CachedSummary {
                boundary,
                summary,
                message_count,
            },
        );
    }

    /// Invalidate the cache for a session. Called on edit/truncate where the
    /// old boundary is no longer valid.
    pub fn invalidate(&self, session_id: &str) {
        let mut guard = self.inner.lock().unwrap();
        guard.remove(session_id);
    }

    /// Invalidate all sessions. Called on provider/model change where summaries
    /// generated by the old model may not be coherent for the new one.
    pub fn invalidate_all(&self) {
        let mut guard = self.inner.lock().unwrap();
        guard.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ff_core::Role;

    fn test_msg(content: &str) -> Message {
        Message {
            id: "test".into(),
            session_id: String::new(),
            role: Role::Assistant,
            content: content.into(),
            tool_calls: None,
            tool_call_id: None,
            attachments: None,
            reasoning: None,
            stop_reason: None,
            author_name: None,
            created_at: 0,
        }
    }

    #[test]
    fn get_returns_none_for_empty_cache() {
        let cache = CompactionCache::new();
        assert!(cache.get("session-1").is_none());
    }

    #[test]
    fn put_then_get_roundtrips() {
        let cache = CompactionCache::new();
        let msg = test_msg("summary of first 10 messages");
        cache.put("s1", 10, msg.clone(), 42);

        let (boundary, retrieved, count) = cache.get("s1").unwrap();
        assert_eq!(boundary, 10);
        assert_eq!(retrieved.content, msg.content);
        assert_eq!(count, 42);
    }

    #[test]
    fn invalidate_removes_session() {
        let cache = CompactionCache::new();
        cache.put("s1", 5, test_msg("x"), 10);
        cache.put("s2", 8, test_msg("y"), 20);

        cache.invalidate("s1");
        assert!(cache.get("s1").is_none());
        assert!(cache.get("s2").is_some());
    }

    #[test]
    fn invalidate_all_clears_everything() {
        let cache = CompactionCache::new();
        cache.put("s1", 5, test_msg("x"), 10);
        cache.put("s2", 8, test_msg("y"), 20);

        cache.invalidate_all();
        assert!(cache.get("s1").is_none());
        assert!(cache.get("s2").is_none());
    }

    #[test]
    fn put_overwrites_existing() {
        let cache = CompactionCache::new();
        cache.put("s1", 5, test_msg("old"), 10);
        cache.put("s1", 12, test_msg("new"), 25);

        let (boundary, msg, count) = cache.get("s1").unwrap();
        assert_eq!(boundary, 12);
        assert_eq!(msg.content, "new");
        assert_eq!(count, 25);
    }

    #[test]
    fn concurrent_access_from_two_threads() {
        use std::sync::Arc;
        use std::thread;

        let cache = Arc::new(CompactionCache::new());
        let c1 = cache.clone();
        let c2 = cache.clone();

        let t1 = thread::spawn(move || {
            for i in 0..100 {
                c1.put("s1", i, test_msg(&format!("msg-{i}")), i as u64);
            }
        });
        let t2 = thread::spawn(move || {
            for _ in 0..100 {
                // Should never panic even under concurrent writes.
                let _ = c2.get("s1");
            }
        });

        t1.join().unwrap();
        t2.join().unwrap();

        // Final state should reflect thread 1'\''s last write.
        let (boundary, _, _) = cache.get("s1").unwrap();
        assert_eq!(boundary, 99);
    }
}
