//! Cross-turn abstractive summary cache (#757).
//!
//! The compaction summarizer produces a summary of the "cold tail" of a
//! conversation. Within a single turn this is already cached (the local
//! `last_summary` variable). But across turns the cache was lost — each new
//! turn re-summarized from scratch even when only 1-2 messages were appended.
//!
//! This module provides a shared, per-session cache that survives across turns
//! so `run_turn` can seed its local state from the previous turn's result.
//!
//! ## Bounded growth (#764)
//!
//! Entries are evicted on an LRU basis once the cache exceeds
//! [`MAX_ENTRIES`] distinct session ids. Cross-turn caching is best-effort:
//! when a session's summary is evicted, its next turn simply re-summarizes
//! from scratch (graceful degradation — no correctness impact, just one extra
//! summarizer round-trip on the cold path).

use std::num::NonZeroUsize;
use std::sync::Mutex;

use ff_core::Message;
use lru::LruCache;

/// Soft cap on the number of distinct sessions tracked. At ~2 KB / entry the
/// worst-case footprint is ~256 KB; the value is comfortably above the number
/// of concurrent sessions any realistic user runs.
const MAX_ENTRIES: NonZeroUsize = NonZeroUsize::new(128).expect("non-zero");

/// Per-session cross-turn compaction summary cache.
///
/// Thread-safe via interior `Mutex` — the lock is held only for the duration
/// of an LRU op (nanoseconds), never across awaits. Only one `run_turn` per
/// session runs at a time (enforced by the cancel-before-spawn invariant
/// upstream), so contention is effectively zero.
pub struct CompactionCache {
    inner: Mutex<LruCache<String, CachedSummary>>,
}

/// The cached summary state for one session.
#[derive(Debug, Clone)]
struct CachedSummary {
    /// Index into the wire at which this summary ends (exclusive). Messages
    /// `[0..boundary]` are covered by the summary; `[boundary..]` are verbatim.
    boundary: usize,
    /// The summary message itself (role=System or User depending on prompt).
    summary: Message,
    /// Transcript message count when the summary was produced. Used by
    /// `summary_due()` to decide whether the cache is stale.
    message_count: u64,
}

impl CompactionCache {
    pub fn new() -> Self {
        Self {
            inner: Mutex::new(LruCache::new(MAX_ENTRIES)),
        }
    }

    /// Retrieve the cached summary for a session, if any. Promotes the entry
    /// to most-recently-used.
    pub fn get(&self, session_id: &str) -> Option<(usize, Message, u64)> {
        let mut guard = self.inner.lock().unwrap();
        guard
            .get(session_id)
            .map(|c| (c.boundary, c.summary.clone(), c.message_count))
    }

    /// Store (or overwrite) the summary for a session. When the cache is at
    /// capacity, the least-recently-touched entry is silently dropped.
    pub fn put(&self, session_id: &str, boundary: usize, summary: Message, message_count: u64) {
        let mut guard = self.inner.lock().unwrap();
        guard.put(
            session_id.to_owned(),
            CachedSummary {
                boundary,
                summary,
                message_count,
            },
        );
    }

    /// Invalidate the cache for a session. Called on edit/truncate where the
    /// old boundary is no longer valid.
    pub fn invalidate(&self, session_id: &str) {
        let mut guard = self.inner.lock().unwrap();
        guard.pop(session_id);
    }

    /// Invalidate all sessions. Called on provider/model change where summaries
    /// generated by the old model may not be coherent for the new one.
    pub fn invalidate_all(&self) {
        let mut guard = self.inner.lock().unwrap();
        guard.clear();
    }
}

impl Default for CompactionCache {
    fn default() -> Self {
        Self::new()
    }
}

// `LruCache::iter_mut` would let consumers iterate, but the cache deliberately
// exposes only the four mutating ops above so eviction stays encapsulated.
#[cfg(test)]
mod tests;
