[package]
name = "ff-signals"
version = "1.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ff-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ts-rs = { workspace = true, features = ["serde-json-impl"] }

[dev-dependencies]
tempfile = { workspace = true }
