[package]
name = "ff-agent"
version = "1.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ff-core = { workspace = true }
ff-llm = { workspace = true }
ff-memory = { workspace = true }
ff-session = { workspace = true }
ff-skills = { workspace = true }
ff-tools = { workspace = true }
serde = { workspace = true }
minijinja = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
iana-time-zone = { workspace = true }
lru = { workspace = true }

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["test-util"] }
