// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trust level of a tool call that requires user approval. Read-only calls never
 * reach approval, so this enum carries only the gated levels — it is the typed
 * contract for [`ToolApprovalRequestEvent::safety`].
 */
export type ApprovalSafety = "write" | "sensitive" | "dangerous" | "publish";
