// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an [`Attachment`] is, so a provider/UI can route it (vision vs. document).
 */
export type AttachmentKind = "image" | "document";
