// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an attachment's bytes live. A `Path` reference is preferred — it keeps the
 * transcript and the database small, with base64 materialized only at provider
 * send time. `Inline` carries base64 directly for sources that have no file on
 * disk (e.g. a clipboard paste).
 */
export type AttachmentSource = { "type": "path", "value": string } | { "type": "inline", "value": string };
