// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentKind } from "./AttachmentKind";
import type { AttachmentSource } from "./AttachmentSource";

/**
 * A file attached to a message (image or document). Round-trips through
 * persistence and bridges to each provider's wire format at send time. Foundation
 * for multimodal support (#332); providers consume it in their own tickets.
 */
export type Attachment = { kind: AttachmentKind, 
/**
 * IANA media type, e.g. "image/png" or "application/pdf".
 */
mediaType: string, source: AttachmentSource, 
/**
 * Original file name, when known.
 */
name?: string, 
/**
 * Size of the payload in bytes.
 */
bytes: number, };
