// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a Bedrock connection authenticates. All three resolve credentials
 * backend-side; secret material (secret access key, session token, bearer API
 * key) lives in the OS keychain and never on this contract.
 */
export type BedrockAuth = "profile" | "iamKeys" | "apiKey";
