// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named internal action a built-in task runs, as opposed to a free-text
 * prompt. Dispatch + seeding is #544; the type lives here so the FE `Builtin`
 * badge has a contract from the start.
 */
export type BuiltinAction = "memory_consolidate";
