// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One source segment of a confluence session (#1229, RFC 0023 §4/§5): a
 * session that was concatenated into it, and the number of messages it
 * contributed. Ordered within [`Session::confluence_sources`] by append order.
 */
export type ConfluenceSource = { 
/**
 * The session this segment was copied from. Always `Some` when a confluence
 * is created: V1 requires every source to exist (a missing one aborts with
 * `SessionNotFound`). `None` is reserved for a source deleted *after* the
 * confluence — the segment stays, its exact origin is simply lost.
 */
sessionId?: string, 
/**
 * How many messages this source contributed, i.e. the length of its
 * contiguous span in the confluence transcript.
 */
messageCount: number, };
