// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A transient connection failure ended the turn -- budget exhausted or a mid-stream
 * drop (no resume) (#928). Distinct from `TurnErrorEvent` so the frontend can render
 * a connection-specific error + "Try again" (a re-run). `message` is the underlying
 * error for detail; the user-facing headline copy is owned by the frontend and must
 * stay provider-neutral (offline vs provider-down are indistinguishable here).
 */
export type ConnectionFailedEvent = { sessionId: string, messageId: string, message: string, };
