// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the effective served context window was determined, in precedence order
 * (#602). `Explicit` = the `FLOWFORGE_OLLAMA_NUM_CTX` override; `Served` = probed
 * from the live Ollama runtime via `/api/ps`; `Default` = the conservative
 * [`crate::DEFAULT_CONTEXT_WINDOW_TOKENS`] fallback (model not loaded or the probe
 * failed). Serializes to the matching camelCase string the FE union expects.
 */
export type ContextWindowSource = "explicit" | "served" | "default";
