// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `chars/4` context-size estimate at turn end, split into the three
 * component buckets the context-usage popover renders (#931): the transient
 * system prompt, the advertised tool schemas, and the persisted message
 * transcript. Proportions drive the segmented bar; the popover shows each
 * bucket's token count and share of the budget.
 */
export type ContextBreakdown = { 
/**
 * Estimated tokens of the system prompt (persona + skills + ambient context).
 */
systemTokens: number, 
/**
 * Estimated tokens of the advertised tool schemas.
 */
toolTokens: number, 
/**
 * Number of tool specs advertised this turn.
 */
toolSpecs: number, 
/**
 * Estimated tokens of the persisted message transcript (user/assistant/tool).
 */
messageTokens: number, 
/**
 * Number of messages in the transcript.
 */
messageCount: number, };
