// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `chars/4` context-size estimate at turn end, split into the three
 * component buckets the context-usage popover renders (#931): the transient
 * system prompt, the advertised tool schemas, and the persisted message
 * transcript. Proportions drive the segmented bar; the popover shows each
 * bucket's token count and share of the budget.
 */
export type ContextBreakdown = { 
/**
 * Estimated tokens of the system prompt (persona + skills + ambient context).
 */
systemTokens: number, 
/**
 * Estimated tokens of the advertised tool schemas.
 */
toolTokens: number, 
/**
 * Number of tool specs advertised this turn.
 */
toolSpecs: number, 
/**
 * Estimated tokens of the **verbatim** persisted message transcript
 * (user/assistant/tool) — the store, before any compaction. Formerly
 * `messageTokens`; renamed to distinguish from `wireTokens` (#997).
 */
verbatimTokens: number, 
/**
 * Estimated tokens of the **compacted wire** actually sent to the model this
 * turn (post Tier-1 extractive + Tier-2 abstractive). This is what `pctUsed`
 * should be computed from — it reflects prefill cost, not store size (#997).
 */
wireTokens: number, 
/**
 * Number of messages in the verbatim transcript.
 */
messageCount: number, 
/**
 * Estimated tokens of the **Mid** layer of the wire (#1045): the folded
 * timeline covering everything older than the verbatim tail. `0` when no
 * fold has happened yet (the whole transcript is still Near).
 */
midTokens?: number, 
/**
 * Estimated tokens of the **Near** layer of the wire (#1045): the
 * token-budgeted verbatim tail. Equals `wire_tokens` minus the Mid layer
 * (system/tools are separate buckets). `None` when not assessed.
 */
nearTokens?: number, };
