// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SafetyCeiling } from "./SafetyCeiling";
import type { TaskKind } from "./TaskKind";

/**
 * Payload for `create_scheduled_task`. Carries the fields the New-task form
 * collects; `id`/derived fields are server-assigned.
 */
export type CreateScheduledTaskInput = { name: string, cron: string, kind: TaskKind, workspace?: string, profile?: string, safetyCeiling: SafetyCeiling, };
