// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Usage-driven decay configuration (RFC 0007 §5). Each knob has a conservative
 * default; the whole mechanism is gated by `enabled`.
 *
 * M6.0 is observe-only: stats are recorded, but `weight` only decays/reinforces
 * when `enabled = true`. `enabled` defaults to `false` (issue #291) so the
 * foundation slice is a no-op rollback path; M6.1 flips it on with dormancy.
 * `ambient_gain` and `dormant_threshold` are part of the schema now but are not
 * consumed until M6.1.
 */
export type DecayConfig = { 
/**
 * Master switch for decay + reinforcement (RFC 0007 §5). When `false`,
 * stats are still recorded but `weight` is never modified.
 */
enabled: boolean, 
/**
 * Daily multiplier applied per idle day: `weight *= factor.powf(days)`
 * (~35-day half-life at 0.98).
 */
factor: number, 
/**
 * Strength of a `memory_search` hit: `weight += gain * (1.0 - weight)`.
 */
reinforceGain: number, 
/**
 * Weaker reinforcement for an ambient-only hit (schema now; consumed M6.1).
 */
ambientGain: number, 
/**
 * `weight` below this marks a chunk dormant (schema now; consumed M6.1).
 */
dormantThreshold: number, };
