// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Usage-driven decay configuration (RFC 0007 §5). Each knob has a conservative
 * default; the whole mechanism is gated by `enabled`.
 *
 * `weight` only decays/reinforces when `enabled = true`. M6.0 (#291) shipped
 * `enabled = false` as a no-op rollback path; M6.1 (#292) flips the default on
 * and consumes `dormant_threshold` to skip dormant chunks from ambient
 * injection. `ambient_gain` (weak ambient reinforcement, RFC §10.1) is schema
 * now, consumed in a follow-up.
 */
export type DecayConfig = { 
/**
 * Master switch for decay + reinforcement (RFC 0007 §5). When `false`,
 * stats are still recorded but `weight` is never modified.
 */
enabled: boolean, 
/**
 * Daily multiplier applied per idle day: `weight *= factor.powf(days)`
 * (~35-day half-life at 0.98).
 */
factor: number, 
/**
 * Strength of a `memory_search` hit: `weight += gain * (1.0 - weight)`.
 */
reinforceGain: number, 
/**
 * Weaker reinforcement for an ambient-only hit (schema now; consumed in
 * the ambient-reinforcement follow-up, RFC §10.1).
 */
ambientGain: number, 
/**
 * `weight` below this marks a chunk dormant — skipped from ambient
 * injection while staying recallable (RFC 0007 §M6.1).
 */
dormantThreshold: number, };
