// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a directory listing returned by `list_directory`. Directories
 * report `size: 0`; the frontend sorts directories first, then alphabetically.
 */
export type DirEntry = { 
/**
 * File or directory name without any directory prefix, e.g. `main.rs`.
 */
name: string, 
/**
 * Whether this entry is a directory.
 */
isDir: boolean, 
/**
 * Size on disk in bytes; `0` for directories.
 */
size: number, };
