// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a phenotype may use network-capable tools.
 *
 * - [`Egress::Open`] — all tools advertised (today's behaviour). The default, so
 *   existing phenotypes and on-disk TOML that omit `egress` are unchanged.
 * - [`Egress::LocalOnly`] — network-capable tools are stripped from the advertised
 *   set, the same way Plan mode strips non-ReadOnly tools. Fail-safe: a tool is
 *   treated as network-capable unless it proves otherwise (see
 *   [`crate::permission`]-adjacent `Tool::reaches_network` in `ff-tools`).
 *
 * Serializes as `camelCase` (`open` / `localOnly`) for a consistent TS binding
 * with [`crate::Mode`]; a `local-only` alias is accepted on read so the RFC 0013
 * TOML literal (`egress = "local-only"`) still deserializes.
 */
export type Egress = "open" | "localOnly";
