// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";

/**
 * The active phenotype is `LocalOnly` but the resolved inference path is a
 * hosted provider (#888). The egress policy strips network-capable *tools*
 * (RFC 0013 / #883) but the inference call itself still leaves the machine
 * when the model is hosted — prompt content (potentially PII) reaches the
 * cloud regardless of the tool layer. The frontend renders this as a
 * privacy warning (badge, banner, or inline notice) so the user can either
 * switch to a local connection or accept the inference egress explicitly.
 * Mirrors the `AttachmentsDropped` precedent: surfaced via a typed event so
 * the silent capability gap doesn't go unnoticed. Emitted once per turn
 * (first iteration only) on the `egress:mismatch` IPC channel.
 */
export type EgressMismatchEvent = { sessionId: string, messageId: string, 
/**
 * The resolved provider kind (e.g. `openAi`, `siliconFlow`, `bedrock`).
 * Frontends use this to render the warning with the right "hosted by"
 * label.
 */
kind: ProviderKind, 
/**
 * The model id resolved at turn start. Useful when a phenotype override
 * swaps the model away from the global default, so the warning can name
 * the actual model leaving the machine.
 */
model: string, };
