// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where chunk embeddings come from (M5.3). `Local` is the default on-device
 * path; `Cloud` is reserved for the M5.3.2 hosted embedder.
 */
export type EmbeddingProvider = "local" | "cloud";
