// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingProvider } from "./EmbeddingProvider";

/**
 * Hybrid recall configuration (RFC 0006, M5.3). When `enabled = false`
 * (the default) recall is byte-identical to the FTS5/BM25 path.
 */
export type EmbeddingsConfig = { 
/**
 * Opt in to semantic recall. Off keeps the FTS-only behaviour.
 */
enabled: boolean, 
/**
 * Which embedder backs semantic recall when `enabled`.
 */
provider: EmbeddingProvider, };
