// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rough cost projection shown alongside an optimize proposal (RFC 0001 §8). Both
 * values use the same coarse token proxy as the telemetry substrate, so they are
 * comparable to each other but approximate in absolute terms (real provider usage
 * lands in M4). `estimatedMeanTokens` scales the current rolling mean by the body's
 * size change; `0.0` when the skill has no telemetry yet.
 */
export type EvolveCostEstimate = { currentMeanTokens: number, estimatedMeanTokens: number, };
