// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of [`ProposePrScope::per_file`] — a single file's line churn (#1252).
 */
export type FileScope = { 
/**
 * Repo-relative path as git reports it.
 */
path: string, 
/**
 * Lines added in this file.
 */
insertions: number, 
/**
 * Lines removed in this file.
 */
deletions: number, };
