// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file's body returned by `read_file`. `text` is `None` for binary (non-UTF-8)
 * files, in which case `is_binary` is `true`; `truncated` is set when the file is
 * larger than the requested byte cap and only a prefix is returned.
 */
export type FileContent = { 
/**
 * UTF-8 decoded contents (a prefix when `truncated`); `None` when `is_binary`.
 */
text: string | null, 
/**
 * Whether the file was detected as binary (non-UTF-8) and so not decoded.
 */
isBinary: boolean, 
/**
 * Whether `text` holds only the first `max_bytes` of a larger file.
 */
truncated: boolean, 
/**
 * Full size of the file on disk in bytes, regardless of truncation.
 */
size: number, };
