// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The serialization target for [`export_session`](../../ff_session). `Json` is a
 * lossless, round-trippable dump of the session and its transcript; `Markdown` is
 * a folded, human-readable transcript for sharing or archiving (RFC 0012, #278).
 */
export type Format = "markdown" | "json";
