// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stop conditions for a goal loop (RFC 0020 §3). A `None` optional dimension is
 * unbounded; `max_iterations` always has a value (default
 * [`DEFAULT_MAX_ITERATIONS`]).
 */
export type GoalBudget = { maxIterations: number, maxTokens?: number, maxWallMs?: number, };
