// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of a goal (RFC 0020 §5.1).
 */
export type GoalStatus = "active" | "paused" | "completed" | "failed" | "exhausted";
