// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cumulative spend across a goal's iterations (RFC 0020 §3, §10: per-goal, not
 * per-iteration).
 */
export type GoalSpend = { tokens: number, wallMs: number, };
