// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalBudget } from "./GoalBudget";
import type { GoalLedgerEntry } from "./GoalLedgerEntry";
import type { GoalSpend } from "./GoalSpend";
import type { GoalStatus } from "./GoalStatus";

/**
 * A persistent autonomous objective bound to one session (#683, RFC 0020 §3).
 *
 * Persisted to `<goals_dir>/<session_id>.json`. Only `session_id`, `objective`,
 * and `status` are truly required to read a file back; every other field has a
 * serde default so an older/partial file stays forward-compatible.
 */
export type Goal = { sessionId: string, 
/**
 * The objective text the loop iterates toward.
 */
objective: string, status: GoalStatus, 
/**
 * Completed iterations so far; bumped at each iteration boundary.
 */
iteration: number, budget: GoalBudget, 
/**
 * Cumulative usage across all iterations, checked against `budget`.
 */
spent: GoalSpend, 
/**
 * The evidence-first ledger (#74). Each fresh-context iteration reads it,
 * advances one entry, and writes back result + evidence + verdict. Empty
 * until the loop records its first step.
 */
ledger: Array<GoalLedgerEntry>, 
/**
 * A user steer to fold into the next iteration (RFC 0020 §6); cleared once
 * consumed. Distinct from a normal turn — it refines the objective without
 * racing the loop.
 */
pendingSteer?: string, 
/**
 * A shell command the loop runs to *verify* a claimed completion before it
 * accepts `goal_complete` (RFC 0020 §5.1, #684 D3). `None` keeps the pre-D3
 * behaviour — a `goal_complete` is trusted as-is — so non-code goals (a
 * research write-up) are unaffected. When set, the loop runs it on a
 * completion signal: a green exit accepts `Completed`; a non-zero exit
 * rejects the claim, records a `Drift` ledger entry carrying the command's
 * output as evidence, and lets the loop keep iterating.
 */
verifyCmd?: string, createdMs: number, updatedMs: number, };
