// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NextAction } from "./NextAction";
import type { StepStatus } from "./StepStatus";
import type { Verdict } from "./Verdict";

/**
 * One evidence-first step in the goal ledger (#74; shape adopted from the
 * discussion, incl. @HarperZ9). A fresh iteration reconstructs progress from
 * these entries rather than a prose summary, and a human can see exactly where
 * the loop moved from evidence to judgment.
 */
export type GoalLedgerEntry = { 
/**
 * Stable id so a step can be updated in place across iterations.
 */
id: string, status: StepStatus, 
/**
 * What this step is supposed to prove or change.
 */
claim: string, 
/**
 * What the agent attempted. `None` until the step is acted on.
 */
action?: string, 
/**
 * Evidence pointers: command output, a test path, a diff, a URL, an artifact
 * id. Empty until the step produces evidence.
 */
evidence: Array<string>, 
/**
 * The verdict once checked. `None` while pending/active. An explicit
 * [`Verdict::Unverifiable`] is required rather than omission, so the next
 * run never inherits confidence without evidence (#74).
 */
verdict?: Verdict, 
/**
 * What the loop should do next for this step. `NextAction::AskUser` is the
 * sanctioned circuit breaker (#74) and the join point with the headless
 * `needs_attention` outcome (RFC 0017 §3.1/§8.4).
 */
next?: NextAction, createdMs: number, updatedMs: number, };
