// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an `http` observer decides when to fire.
 *
 * `HttpSource` began as a pure change detector, which cannot express the most
 * common reactive need — "wake me when this server comes up" — because the
 * first successful poll only records a baseline and an unchanged body never
 * fires again (#954 item 4). `Ready` mode adds that missing semantic.
 */
export type HttpMode = "change" | "ready";
