// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KernelLiveState } from "./KernelLiveState";

/**
 * One kernel's structured state within a session — the per-tab data for the
 * multi-kernel switcher (#871 FE-2 / #923). Mirrors the per-kernel fields the
 * representative exposes on [`NotebookKernelState`], but for every kernel.
 */
export type KernelInfo = { 
/**
 * The kernel's id (e.g. `kernel-abcd1234`).
 */
kernelId: string, 
/**
 * The kernel's lifecycle (`running` / `dead`).
 */
state: KernelLiveState, 
/**
 * The kernel's process id; null when unavailable.
 */
pid: number | null, 
/**
 * Cells this kernel has executed so far.
 */
executionCount: number, };
