// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a single kernel as surfaced to the desktop status panel (#871).
 * `"dead"` reflects a kernel that died on its own (EOF on its pipe); a user
 * Stop reaps the session instead, so it never produces `Dead`.
 */
export type KernelLiveState = "running" | "dead";
