// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpScope } from "./McpScope";

/**
 * One external MCP server definition, as it appears in `~/.flowforge/mcp.json`
 * (Claude/Cursor `mcpServers` shape).
 */
export type McpServerConfig = { id: string, command: string, args: Array<string>, env: { [key in string]?: string }, disabled: boolean, scope: McpScope, };
