// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerStatus } from "./McpServerStatus";

/**
 * Backend -> frontend notice that one or more MCP servers changed status (a
 * start/stop/restart, a connect failure, or an enable/disable/add/remove reload).
 * Carries the full status snapshot so the frontend replaces its state rather than
 * diffing, mirroring [`SkillsChangedEvent`]. The server definitions themselves are
 * re-fetched via `list_mcp_servers`.
 */
export type McpStatusChangedEvent = { servers: Array<McpServerStatus>, };
