// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerState } from "./McpServerState";

/**
 * A snapshot of one server's status for the UI / supervisor.
 */
export type McpServerStatus = { id: string, state: McpServerState, toolCount: number, lastError?: string, restarts: number, pid?: number, };
