// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of a supervised MCP server (RFC 0003 §5). The supervisor (M4.2)
 * drives the transitions; M4.0 only ever reports `Running` (or surfaces a connect
 * failure as an error).
 */
export type McpServerState = "starting" | "running" | "restarting" | "failed" | "disabled";
