// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an MCP server instance is keyed (RFC 0018 §4.1). `Global` keeps RFC 0003's
 * one-instance-per-id semantics; `Workspace` runs one instance per distinct
 * workspace root. Absent in `mcp.json` means `Global`, so existing configs are
 * unchanged.
 */
export type McpScope = "global" | "workspace";
