// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tool advertised by an MCP server (RFC 0003 §4). `input_schema` is the raw
 * JSON Schema the server reports, carried verbatim onto the bridged tool (M4.3) so
 * the model gets accurate argument typing.
 */
export type McpToolInfo = { 
/**
 * The id of the server that advertised this tool.
 */
server: string, 
/**
 * The bare tool name as the server reports it (before `mcp__<server>__` namespacing).
 */
name: string, description: string, inputSchema: unknown, };
