// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecayConfig } from "./DecayConfig";
import type { EmbeddingsConfig } from "./EmbeddingsConfig";

/**
 * Memory behaviour knobs. Defaults make memory on with a small ambient budget;
 * `enabled = false` is the full disable path (RFC 0006 §8).
 *
 * Note (M5.3.x persistence): `rename_all = "camelCase"` is safe today because
 * this is only ever built via `Default` and never deserialized from disk. When
 * on-disk persistence lands, keep the file camelCase too (or add an explicit
 * migration) so a snake_case settings file isn't silently reintroduced.
 */
export type MemoryConfig = { enabled: boolean, 
/**
 * Byte budget for the curated section of the ambient block (a pragmatic
 * stand-in for a token budget). The curated file is truncated to a
 * line-boundary head past this, with a pointer to `memory_search`.
 */
injectionBudgetBytes: number, 
/**
 * Hybrid (semantic) recall settings (M5.3). Off by default: recall stays
 * pure FTS5/BM25 until a user opts in and an embedder is wired.
 */
embeddings: EmbeddingsConfig, 
/**
 * Whether the consolidation pass may hard-evict (demote) the lowest-salience
 * curated facts back to the daily log when merge + promote alone cannot bring
 * the curated file under `injection_budget_bytes` (RFC 0007 sec 6). Demotion
 * never deletes: the entry is appended to today's daily log (still FTS-indexed,
 * still found by `memory_search`) and removed from curated. Default on now;
 * M6.1 flips this off once decay/dormancy governs injection instead.
 */
evictToBudget: boolean, 
/**
 * Usage-driven decay knobs (RFC 0007 §5). Disabled by default in M6.0:
 * statistics are recorded but never decayed, so behaviour is byte-identical
 * to M5. M6.1 flips this default on once dormancy consumes `weight`.
 */
decay: DecayConfig, };
