// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of the memory store, returned by `memory_overview` to drive the Settings
 * pane header (file/byte counts, root location, and whether capture is enabled).
 */
export type MemoryOverview = { 
/**
 * Whether memory capture is enabled. Read-only here; the toggle lands with the
 * settings work (Issue #166).
 */
enabled: boolean, 
/**
 * Number of memory files across all layers.
 */
fileCount: number, 
/**
 * Total size of all memory files in bytes.
 */
totalBytes: number, 
/**
 * Absolute path to the memory root directory.
 */
rootPath: string, };
