// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryFileKind } from "./MemoryFileKind";

/**
 * Metadata for a single memory file, listed by `list_memory_files`. The body is
 * fetched separately via `read_memory_file` so listings stay cheap.
 */
export type MemoryFileInfo = { 
/**
 * File name without directory, e.g. `MEMORY.md` or `2026-06-18.md`.
 */
name: string, 
/**
 * Path relative to the memory root, with forward slashes, e.g.
 * `daily/2026-06-18.md`. Pass this back to `read_memory_file`.
 */
relPath: string, 
/**
 * Which layer this file belongs to.
 */
kind: MemoryFileKind, 
/**
 * Size on disk in bytes.
 */
sizeBytes: number, 
/**
 * Last-modified time as Unix epoch milliseconds.
 */
modifiedMs: number, };
