// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which memory layer a [`MemoryFileInfo`] belongs to. Mirrors the ff-memory
 * `MemoryFileKind`, kept separate so the wire contract owns its own derives.
 */
export type MemoryFileKind = "curated" | "daily";
