// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A silent context-pressure memory flush wrote durable facts to the user's
 * on-disk memory mid-turn (#283, follow-up to #244 R5). Emitted only when the
 * flush actually wrote something, so the memory browser can surface provenance
 * ("memory auto-updated this turn").
 */
export type MemoryFlushedEvent = { sessionId: string, messageId: string, 
/**
 * Number of durable facts written this turn (always > 0 when emitted).
 */
writes: number, };
