// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingsConfig } from "./EmbeddingsConfig";

/**
 * Memory behaviour knobs. Defaults make memory on with a small ambient budget;
 * `enabled = false` is the full disable path (RFC 0006 §8).
 */
export type MemoryConfig = { enabled: boolean, 
/**
 * Byte budget for the curated section of the ambient block (a pragmatic
 * stand-in for a token budget). The curated file is truncated to a
 * line-boundary head past this, with a pointer to `memory_search`.
 */
injectionBudgetBytes: number, 
/**
 * Hybrid (semantic) recall settings (M5.3). Off by default: recall stays
 * pure FTS5/BM25 until a user opts in and an embedder is wired.
 */
embeddings: EmbeddingsConfig, };
