// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-chunk salience stats for the Settings "Salience" surface (Issue #293,
 * RFC 0007 §7). One row per indexed memory chunk, joining the chunk's identity
 * with its `chunk_stats` usage. The backend computes `weight` (effective,
 * pin-aware) and `dormant` authoritatively so the frontend never re-derives the
 * dormancy threshold.
 *
 * **No-row (never recalled) case:** a chunk that has been indexed but never
 * surfaced by `memory_search` has no `chunk_stats` row, so it reads
 * `weight = 1.0`, `access_count = 0`, `last_accessed_ms = None`,
 * `dormant = false`, `pinned = false`. The age clock starts at first *recall*,
 * not creation — the UI should render "never recalled" rather than an epoch
 * timestamp.
 */
export type MemoryChunkStat = { 
/**
 * Stable chunk identity (`ff_memory::chunk_key`) — the mutation handle for
 * `resetMemoryChunk` / `setMemoryChunkPinned`.
 */
chunkKey: string, 
/**
 * Path relative to the memory root, forward slashes, e.g. `MEMORY.md` or
 * `daily/2026-06-25.md`.
 */
relPath: string, 
/**
 * Nearest Markdown heading, or `None` for pre-heading preamble.
 */
heading: string | null, 
/**
 * First non-empty content line of the chunk, trimmed and length-capped — a
 * human-readable summary for the list row.
 */
preview: string, 
/**
 * Effective (decayed, pin-aware) weight — NOT the raw stored
 * `chunk_stats.weight`. A pinned chunk reads `1.0`.
 */
weight: number, 
/**
 * Times this chunk has been reinforced by a recall.
 */
accessCount: number, 
/**
 * Last-recalled time as Unix epoch milliseconds, or `None` if never recalled.
 */
lastAccessedMs: number | null, 
/**
 * Server-computed: `decay.enabled && weight < threshold && !pinned`.
 */
dormant: boolean, 
/**
 * Whether the chunk is pinned (weight held at `1.0`, decay skipped).
 */
pinned: boolean, };
