// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { ToolCall } from "./ToolCall";

export type Message = { id: string, sessionId: string, role: Role, content: string, 
/**
 * Present on an assistant message that requested tool calls.
 */
toolCalls?: Array<ToolCall>, 
/**
 * Present on a `Role::Tool` message, binding the result to its request.
 */
toolCallId?: string, 
/**
 * Unix epoch milliseconds.
 */
createdAt: number, };
