// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { Role } from "./Role";
import type { StopReason } from "./StopReason";
import type { ToolCall } from "./ToolCall";

export type Message = { id: string, sessionId: string, role: Role, content: string, 
/**
 * Present on an assistant message that requested tool calls.
 */
toolCalls?: Array<ToolCall>, 
/**
 * Present on a `Role::Tool` message, binding the result to its request.
 */
toolCallId?: string, 
/**
 * Files attached to this message (multimodal, #332). Absent for a plain
 * text message; omitted from the wire/binding when none.
 */
attachments?: Array<Attachment>, 
/**
 * The model's chain-of-thought for an assistant turn, captured from the
 * reasoning stream so it can be round-tripped to reasoning-capable providers
 * on later tool-calling turns (#375). Absent for non-reasoning turns; stored
 * verbatim and omitted from the wire/binding when none.
 */
reasoning?: string, 
/**
 * Why this assistant turn ended without a usable answer (#658). Present only
 * on a stopped turn's finalized notice message; lets the frontend classify
 * and render the stop structurally instead of string-matching `content`.
 * Omitted from the wire/binding when absent.
 */
stopReason?: StopReason, 
/**
 * Unix epoch milliseconds.
 */
createdAt: number, };
