// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type Message = { id: string, sessionId: string, role: Role, content: string, 
/**
 * Unix epoch milliseconds.
 */
createdAt: number, };
