// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resolved `(connection, model)` pair -- the unit of model selection at every
 * tier (session / phenotype / global) in RFC 0005 §11. `connection` picks the
 * endpoint + credentials; `model` is the model to run on it. Capabilities (e.g.
 * vision) are derived from the connection's `kind` + this `model` via
 * [`model_supports_vision`], never stored on the selection.
 */
export type ModelSelection = { connection: string, model: string, };
