// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much autonomy the agent has before it touches the world.
 *
 * - [`Mode::Plan`] advertises only `Safety::ReadOnly` tools, so the model cannot
 *   even see — let alone call — anything that mutates. Safe by construction.
 * - [`Mode::Act`] advertises the full registry; Write calls go through the approval
 *   gate and Dangerous calls always prompt. This is FlowForge's historical behaviour.
 * - [`Mode::Auto`] advertises the full registry and auto-approves Write, but
 *   Dangerous calls still always prompt. The factory default.
 */
export type Mode = "plan" | "act" | "auto";
