// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much autonomy the agent has before it touches the world. The per-tier
 * approval outcome is set by the permission matrix (RFC 0019 §3); the summaries
 * below describe its default cells.
 *
 * - [`Mode::Plan`] advertises only `Safety::ReadOnly` tools, so the model cannot
 *   even see — let alone call — anything that mutates. Safe by construction.
 * - [`Mode::Act`] advertises the full registry; ReadOnly, Write, and Sensitive
 *   are auto-approved and Dangerous prompts for confirmation. Full access.
 * - [`Mode::Auto`] advertises the full registry; ReadOnly and Write are
 *   auto-approved, Sensitive prompts, and Dangerous is denied. The factory default.
 */
export type Mode = "plan" | "act" | "auto";
