// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KernelInfo } from "./KernelInfo";
import type { KernelLiveState } from "./KernelLiveState";

/**
 * Single-kernel snapshot of a session's `notebook_runner` state for the desktop
 * status panel (#871). This is the canonical ts-rs source for the shape the FE
 * previously carried as a hand-written stub.
 *
 * A session may hold up to [`MAX_KERNELS_PER_SESSION`] kernels (Phase 3), but
 * the panel's contract is single-kernel: the typed fields describe a
 * representative kernel (a live one if any, else the first by id), while
 * [`raw`](Self::raw) carries the full canonical multi-line status text so no
 * kernel is hidden when several are live.
 */
export type NotebookKernelState = { sessionId: string, 
/**
 * False when the session has no kernel; the remaining fields are then
 * null/zero. True means `state`, `kernel_id`, and `pid` describe the
 * representative kernel.
 */
hasKernel: boolean, 
/**
 * The representative kernel's lifecycle; null when there is no kernel.
 */
state: KernelLiveState | null, 
/**
 * The representative kernel's id (e.g. `kernel-abcd1234`); null when none.
 */
kernelId: string | null, 
/**
 * The representative kernel's process id; null when none or unavailable.
 */
pid: number | null, 
/**
 * Cells executed by the representative kernel so far; zero when none.
 */
executionCount: number, 
/**
 * The full canonical status text (`kernel <id> — <state>; pid=…; cells
 * executed=…`, one line per kernel). Empty when there is no kernel.
 */
raw: string, 
/**
 * Every kernel in the session, structured (Phase 3 multi-kernel switcher,
 * #871 FE-2 / #923). Sorted by kernel id, so the FE renders a stable tab
 * order. `None` when the session has no kernel; otherwise one entry per
 * kernel (the FE shows tabs only when there's more than one). The
 * representative fields above still describe one of these (a live kernel if
 * any) for the single-kernel panel contract; `kernels` is the superset for
 * the switcher. Optional on the wire so a consumer that only needs the
 * representative can ignore it.
 */
kernels?: Array<KernelInfo>, };
