// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
//
// TEMPORARY HAND-WRITTEN STUB — (#871 FE-1) the matching Rust type
// `ff_core::NotebookKernelState` lands in the backend PR that introduces the
// `notebook_status` / `notebook_stop` IPC commands. The ts-rs generator will
// overwrite this file when that PR lands. The shape below mirrors the proposed
// Rust struct field-for-field so the regenerated file is byte-identical
// (apart from header whitespace) — see issue #871 for the FE-0 contract.
//
// A future FE regen will match this exactly:
//   pub struct NotebookKernelState {
//     pub session_id: SessionId,
//     pub has_kernel: bool,
//     pub state: Option<NotebookKernelStateEnum>,
//     pub kernel_id: Option<String>,
//     pub pid: Option<u32>,
//     pub execution_count: u32,
//     pub raw: String,
//   }
//
// Where `NotebookKernelStateEnum` mirrors the canonical status line parsed in
// `lib/notebook-output.ts::parseKernelStatus`: `Running | Dead`.

/** Live state of the session's `notebook_runner` kernel snapshot (Phase 1,
 *  #863/#871 FE-1). Mirrors the canonical `kernel <id> — <running|dead>;
 *  pid=…; cells executed=…` line parsed by `lib/notebook-output.ts`, but as a
 *  typed struct so the FE never has to re-parse the kernel-state text. */
export type NotebookKernelState = {
  sessionId: string,
  /** False when the session has no kernel yet (`notebook_runner start` not
   *  called, or it was stopped / died). True means `state`, `kernelId`, and
   *  `pid` carry values; `executionCount` is always set. */
  hasKernel: boolean,
  /** Backend-derived state. Always set when `hasKernel`; null otherwise. */
  state: "running" | "dead" | null,
  /** Backend-assigned kernel id (e.g. `kernel-abcd1234`). Null when no kernel. */
  kernelId: string | null,
  /** Backend process pid. Null when no kernel or unavailable. */
  pid: number | null,
  /** Number of cells executed so far in the kernel's lifetime, sourced from
   *  the canonical status line's `cells executed=N` token. Zero when the
   *  kernel exists but no cell has run yet. */
  executionCount: number,
  /** Canonical status line the backend emits — kept verbatim so the FE can
   *  fall back to the existing `parseKernelStatus` view if a future backend
   *  change widens the shape. */
  raw: string,
};
