// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObserverKind } from "./ObserverKind";

/**
 * What the supervisor returns from `list` — the durable, human-readable
 * record of an observer. Distinct from the `ManagedObserver` internals
 * (which hold the live `JoinHandle` + cancel signal + event sender).
 */
export type ObserverInfo = { 
/**
 * `number` on the FE, not `bigint`: observer ids are small monotonic
 * counters, so a JS `number` is exact (mirrors the `u32` process-event
 * ids). Avoids `bigint` friction at the `stop_observer` invoke boundary.
 */
id: number, label: string, kind: ObserverKind, target: string, 
/**
 * RFC 3339 timestamp (chrono serializes to a string); typed as `string` on
 * the FE so we don't need the ts-rs `chrono-impl` feature.
 */
startedAt: string, };
