// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The set of active observers for a session changed (#1038, epic #954 M2):
 * one started, was stopped, or fired. Coarse by design -- the frontend
 * re-runs `list_observers(sessionId)` on receipt rather than diffing. A
 * finer started/fired/stopped event is deferred (would be needed for a
 * fired-observer highlight).
 */
export type ObserverChangedEvent = { sessionId: string, };
