// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The concrete source a `start` call instantiates. Phase 1 only ships
 * [`ObserverKind::File`]; the other variants are placeholders so
 * `ObserverSpec` already has the right shape and Phase 2/3 can fill them in
 * without an API break.
 */
export type ObserverKind = "file" | "http" | "process";
