// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStatus } from "./SessionStatus";

export type OutcomeSignal = { sessionId: string, status: SessionStatus, 
/**
 * Daily `chunk_key`s the session touched, for the signal pipeline to settle
 * memory (#1307). Carried on the signal so the consumer need not look up
 * session state by `session_id`; typically <100 keys per session.
 */
touched: Array<string>, };
