// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStatus } from "./SessionStatus";

export type OutcomeSignal = { sessionId: string, status: SessionStatus, };
