// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which standard stream a live output chunk (#680) came from.
 */
export type OutputStreamKind = "stdout" | "stderr";
