// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMatrixEntry } from "./PermissionMatrixEntry";

/**
 * The Control panel's view of the permission state (#702): the full matrix as a
 * flat cell list. Per-tool overrides (#700) will be added here as a second field.
 */
export type PermissionMatrixView = { cells: Array<PermissionMatrixEntry>, };
