// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionCell } from "./PermissionCell";

/**
 * One per-tool override (#700): the [`PermissionCell`] that replaces the matrix
 * cell for a named tool across all Mode × Safety combinations. Part of the IPC
 * surface (#702).
 */
export type PermissionOverrideEntry = { tool: string, cell: PermissionCell, };
