// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMatrixEntry } from "./PermissionMatrixEntry";
import type { PermissionOverrideEntry } from "./PermissionOverrideEntry";

/**
 * The Control panel's view of the permission state (#702): the full matrix as a
 * flat cell list, plus the per-tool overrides (#700).
 */
export type PermissionMatrixView = { cells: Array<PermissionMatrixEntry>, overrides: Array<PermissionOverrideEntry>, };
