// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mode } from "./Mode";
import type { PermissionCell } from "./PermissionCell";
import type { Safety } from "./Safety";

/**
 * One flattened matrix cell: which [`PermissionCell`] applies at a given
 * [`Mode`] × [`Safety`]. Part of the IPC surface (#702).
 */
export type PermissionMatrixEntry = { mode: Mode, safety: Safety, cell: PermissionCell, };
