// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happens when a tool at a given [`Safety`] tier is invoked in a given
 * [`Mode`].
 */
export type PermissionCell = "allow" | "ask" | "deny";
