// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named, switchable working set: which skills are active, an optional model
 * override, and an optional persona preamble prepended to the system prompt.
 *
 * Named for the genotype/phenotype pairing: installed skills are the latent
 * "genes"; a `Phenotype` is the *expressed* set active in a given context (and
 * what Skill Evolution improves). User-facing surfaces use the short form `pheno`.
 */
export type Phenotype = { name: string, 
/**
 * Active skill names (resolved against the `SkillRegistry`).
 */
skills: Array<string>, 
/**
 * Overrides the default model when set.
 */
model?: string, 
/**
 * Extra system-prompt preamble for this phenotype.
 */
persona?: string, };
