// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Egress } from "./Egress";
import type { McpServerConfig } from "./McpServerConfig";

/**
 * A named, switchable working set: which skills are active, an optional model
 * override, and an optional persona preamble prepended to the system prompt.
 *
 * Named for the genotype/phenotype pairing: installed skills are the latent
 * "genes"; a `Phenotype` is the *expressed* set active in a given context (and
 * what Skill Evolution improves). User-facing surfaces use the short form `pheno`.
 */
export type Phenotype = { name: string, 
/**
 * Active skill names (resolved against the `SkillRegistry`).
 */
skills: Array<string>, 
/**
 * Overrides the default model when set.
 */
model?: string, 
/**
 * Binds this phenotype to a specific provider connection (RFC 0005 Phase C).
 * `None` inherits the globally active connection. Pairs with `model` to form
 * the phenotype tier of three-tier model resolution (RFC 0005 §11.2).
 */
provider?: string, 
/**
 * Extra system-prompt preamble for this phenotype.
 */
persona?: string, 
/**
 * Overrides the agent loop's tool-call iteration cap when set (#244 R3).
 * A coding phenotype that runs long edit/build/test/fix cycles raises this
 * above the default; unset falls back to [`ff_agent`'s default cap].
 */
maxIterations?: number, 
/**
 * Phenotype-tier MCP server definitions (RFC 0018 section 3.1). These overlay
 * the global `mcp.json` by id (whole-record, RFC section 11.5) when this
 * phenotype is active; a `scope: workspace` entry (e.g. codegraph) is keyed
 * per workspace root. Empty contributes nothing, identical to today.
 */
mcpServers: Array<McpServerConfig>, 
/**
 * Network-egress policy (RFC 0013). `Open` (the default) advertises all tools;
 * `LocalOnly` strips network-capable tools from the advertised set so a
 * privacy-restricted phenotype (e.g. `enclave`) cannot leak PII over the
 * network. `#[serde(default)]` keeps existing phenotypes / TOML that omit the
 * field on `Open`, i.e. unchanged.
 */
egress: Egress, };
