// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend -> frontend notice that a just-activated phenotype lists a skill whose
 * declared MCP server is unavailable (#301/#235) -- absent from `mcp.json`, or
 * present but not `Running`. Mirrors the warn-only signal `warn_missing_skill_mcp`
 * logs; emitted only when the unavailable list is non-empty so the frontend toast
 * fires exactly when there is something to report. Non-fatal: activation never
 * blocks and the skill's grep/glob fallbacks still work. `servers` is name-sorted
 * and deduplicated.
 */
export type PhenotypeMcpUnavailableEvent = { phenotype: string, servers: Array<string>, };
