// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend -> frontend notice that entries in an active phenotype's `preheat` list
 * were dropped (#1179 3B) -- an unknown/non-deferrable tool name, or a name that
 * did not fit [`MAX_PREHEAT_BYTES`](ff_tools::MAX_PREHEAT_BYTES).
 *
 * Exists because the alternative is indistinguishable from success: a phenotype
 * with a typo'd tool name preheats nothing, behaves exactly like one with no
 * preheat list, and gives its author no reason to look. Non-fatal -- the tool is
 * still reachable the ordinary way, via `tool_search`.
 *
 * Emitted only when something was actually dropped, so the frontend can toast
 * unconditionally on receipt.
 */
export type PhenotypePreheatDroppedEvent = { phenotype: string, sessionId: string, 
/**
 * Names no registered deferred tool matched.
 */
unknown: Array<string>, 
/**
 * Names dropped for exceeding the byte budget, in declaration order.
 */
overBudget: Array<string>, 
/**
 * Bytes the surviving entries cost, for comparison against the budget.
 */
admittedBytes: number, };
