// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A background process ended (exited, was killed, or failed to run) (#873).
 * Emitted once as `process:exited` after the last `process:output`, when the
 * bridge task sees the output broadcast close. `status` is the supervisor's
 * human-readable label -- `"exited(0)"`, `"exited(3)"`, `"killed"`, or
 * `"failed: <reason>"` -- which the frontend renders as the process's
 * terminal status badge.
 */
export type ProcessExitedEvent = { sessionId: string, processId: number, status: string, };
