// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputStreamKind } from "./OutputStreamKind";

/**
 * One chunk of live stdout/stderr from a background process started via
 * `process_manager action=start` (#873). Emitted as `process:output`,
 * independently of any assistant turn, by a desktop bridge task that
 * subscribes to the process's output broadcast the moment it starts. The
 * frontend appends `delta` to the process's output panel keyed by
 * `process_id`. `stream` is `"stdout"` or `"stderr"`. Unlike the per-turn
 * `token`/`tool:output` events, these keep flowing across turns for the
 * life of the process.
 *
 * `process_id` is the small sequential id `start` returns (fits a `u32`,
 * so the frontend gets a plain `number`, not a `bigint`). `stream` reuses the
 * same [`OutputStreamKind`] the per-turn `tool:output` chunks use.
 */
export type ProcessOutputEvent = { sessionId: string, processId: number, stream: OutputStreamKind, delta: string, };
