// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileScope } from "./FileScope";

/**
 * The `git diff --stat`-style scope shown on a `propose_pr` approval gate
 * (#1252). `propose_pr` commits with `add -A`, so untracked files are counted
 * separately (`git diff --stat HEAD` alone would undercount an all-new-file
 * proposal to an empty scope).
 */
export type ProposePrScope = { 
/**
 * Tracked files with staged/working-tree changes vs `HEAD`.
 */
filesChanged: number, 
/**
 * Total lines added across those files.
 */
insertions: number, 
/**
 * Total lines removed across those files.
 */
deletions: number, 
/**
 * Untracked, non-ignored files that `add -A` will bring into the commit
 * (invisible to `git diff --stat HEAD`).
 */
newFiles: number, 
/**
 * Per-file churn (#1252 AC2), capped and ordered by descending churn so the
 * card shows the biggest touches first. Binary files report `+0 −0` (git
 * numstat emits `-` for them). Untracked new files are not listed here —
 * they are only counted in [`Self::new_files`].
 */
perFile: Array<FileScope>, };
