// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockAuth } from "./BedrockAuth";
import type { ProviderKind } from "./ProviderKind";
import type { ReasoningEffort } from "./ReasoningEffort";
import type { ReasoningVisibility } from "./ReasoningVisibility";

/**
 * One configured provider endpoint. A registry holds several of these so the
 * user can keep, say, a local candle-vLLM and a local Ollama side by side and
 * switch the active one without losing the other's settings.
 *
 * Mirrors [`ProviderConfig`] (the legacy singleton) plus the identity fields
 * (`id`, `display_name`, `vendor`) needed to address it in the registry.
 */
export type ProviderConnection = { 
/**
 * Stable slug used to select this connection as active.
 */
id: string, kind: ProviderKind, 
/**
 * Human-facing label shown in the provider picker.
 */
displayName: string, 
/**
 * Optional vendor descriptor (e.g. `"openai"`, `"openrouter"`) for hosted
 * backends; `None` for the bare local kinds.
 */
vendor?: string, 
/**
 * Endpoint override. `None` = use [`ProviderKind::default_base_url`].
 */
baseUrl?: string, model: string, 
/**
 * Whether an API key is stored for this connection (OS keychain).
 */
hasKey: boolean, 
/**
 * True when the registry believes a key is stored (`has_key`) but the OS
 * keychain no longer returns it — most often because an app rebuild changed
 * the code-signing identity and the keychain ACL denied the new binary.
 * Lets the UI prompt "re-enter your key" instead of failing auth silently.
 * Computed on the read path; never persisted as `true`.
 */
secretMissing: boolean, 
/**
 * When true, request and surface model reasoning/thinking streams (#181).
 */
thinking: boolean, 
/**
 * Reasoning *depth* dial for this connection (#395). Only bites when
 * `thinking` is on; picks the per-backend reasoning token budget in
 * `build_provider`. `#[serde(default)]` keeps pre-#395 registries loading as
 * [`ReasoningEffort::Medium`].
 */
reasoningEffort: ReasoningEffort, 
/**
 * Which loop steps request reasoning for this connection (#549). Only bites
 * when `thinking` is on. `#[serde(default)]` keeps pre-#549 registries
 * loading as [`ReasoningVisibility::All`].
 */
reasoningVisibility: ReasoningVisibility, 
/**
 * Whether the composer warmup nudge (#61) fires for this connection. Default
 * `true` (no regression). Only meaningful for local kinds; the warmup command
 * also gates on [`ProviderKind::is_local`]. Users disable it to avoid sustained
 * GPU use (e.g. on laptop battery). `#[serde(default = "default_warmup_enabled")]`
 * keeps pre-#61 registries loading as `true`.
 */
warmupEnabled: boolean, 
/**
 * Served context window for local Ollama connections, in tokens (#538, #651).
 * `None` ⇒ fall back to `FLOWFORGE_OLLAMA_NUM_CTX`, then the probed window,
 * then the conservative default. Only meaningful for Ollama; clamped to the
 * model's trained ceiling by the served-window resolution. `#[serde(default)]`
 * keeps pre-#651 registries loading as `None`.
 */
numCtx?: number, 
/**
 * AWS region for a Bedrock connection (e.g. `"us-east-1"`); the provider
 * derives `bedrock-runtime.<region>.amazonaws.com` from it. `None` for
 * non-Bedrock kinds.
 */
region?: string, 
/**
 * Bedrock credential mode. `None` for non-Bedrock kinds.
 */
authMode?: BedrockAuth, 
/**
 * AWS named profile for [`BedrockAuth::Profile`] (reads `~/.aws/config`).
 */
awsProfile?: string, 
/**
 * AWS access key id for [`BedrockAuth::IamKeys`]. A non-secret identifier; the
 * paired secret access key and session token live in the keychain, never here.
 */
accessKeyId?: string, 
/**
 * Fast model for compaction/flush LLM calls (#756). When set, memory flush
 * and abstractive summarization use this model instead of the session model.
 * Example: `"global.anthropic.claude-haiku-4-5-20251001-v1:0"` (Bedrock), `"gpt-4o-mini"` (OpenAI).
 */
compactionModel?: string, 
/**
 * Context budget (in tokens) at which compaction engages (#756). When set,
 * overrides the default `model_window * 0.8`. Maps to the UI's
 * "Summarization threshold" slider. `None` = use the computed default.
 */
compactionBudget?: number, 
/**
 * Near-layer verbatim-tail budget in tokens (#1045). The layered-context
 * pass keeps roughly this many tokens of recent messages verbatim and
 * folds older ones into the Mid layer. `None` = built-in default.
 */
nearBudget?: number, };
