// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";

/**
 * Non-secret, persisted LLM provider settings. Serialized as JSON to the app
 * config dir and round-tripped across IPC to drive the settings panel.
 */
export type ProviderConfig = { kind: ProviderKind, 
/**
 * Endpoint override. `None` = use [`ProviderKind::default_base_url`].
 */
baseUrl?: string, 
/**
 * Model id sent on each chat request.
 */
model: string, 
/**
 * Whether an API key is stored for this provider (OS keychain). Always
 * `false` in Phase 1 — the field keeps the contract stable for when hosted
 * providers and secrets land.
 */
hasKey: boolean, };
