// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";

/**
 * One configured provider endpoint. A registry holds several of these so the
 * user can keep, say, a local candle-vLLM and a local Ollama side by side and
 * switch the active one without losing the other's settings.
 *
 * Mirrors [`ProviderConfig`] (the legacy singleton) plus the identity fields
 * (`id`, `display_name`, `vendor`) needed to address it in the registry.
 */
export type ProviderConnection = { 
/**
 * Stable slug used to select this connection as active.
 */
id: string, kind: ProviderKind, 
/**
 * Human-facing label shown in the provider picker.
 */
displayName: string, 
/**
 * Optional vendor descriptor (e.g. `"openai"`, `"openrouter"`) for hosted
 * backends; `None` for the bare local kinds.
 */
vendor?: string, 
/**
 * Endpoint override. `None` = use [`ProviderKind::default_base_url`].
 */
baseUrl?: string, model: string, 
/**
 * Whether an API key is stored for this connection (OS keychain).
 */
hasKey: boolean, 
/**
 * When true, request and surface model reasoning/thinking streams (#181).
 */
thinking: boolean, };
