// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderConnection } from "./ProviderConnection";

/**
 * The full set of configured connections plus a pointer to the active one.
 * Replaces the single [`ProviderConfig`] as the persisted provider contract;
 * switching providers is now non-destructive.
 */
export type ProviderRegistry = { connections: Array<ProviderConnection>, 
/**
 * Id of the connection [`build_provider`](crate) resolves against. Always
 * references one of `connections`.
 */
active: string, };
