// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockAuth } from "./BedrockAuth";
import type { ProviderKind } from "./ProviderKind";

/**
 * One configured provider endpoint. A registry holds several of these so the
 * user can keep, say, a local candle-vLLM and a local Ollama side by side and
 * switch the active one without losing the other's settings.
 *
 * Mirrors [`ProviderConfig`] (the legacy singleton) plus the identity fields
 * (`id`, `display_name`, `vendor`) needed to address it in the registry.
 */
export type ProviderConnection = { 
/**
 * Stable slug used to select this connection as active.
 */
id: string, kind: ProviderKind, 
/**
 * Human-facing label shown in the provider picker.
 */
displayName: string, 
/**
 * Optional vendor descriptor (e.g. `"openai"`, `"openrouter"`) for hosted
 * backends; `None` for the bare local kinds.
 */
vendor?: string, 
/**
 * Endpoint override. `None` = use [`ProviderKind::default_base_url`].
 */
baseUrl?: string, model: string, 
/**
 * Whether an API key is stored for this connection (OS keychain).
 */
hasKey: boolean, 
/**
 * When true, request and surface model reasoning/thinking streams (#181).
 */
thinking: boolean, 
/**
 * AWS region for a Bedrock connection (e.g. `"us-east-1"`); the provider
 * derives `bedrock-runtime.<region>.amazonaws.com` from it. `None` for
 * non-Bedrock kinds.
 */
region?: string, 
/**
 * Bedrock credential mode. `None` for non-Bedrock kinds.
 */
authMode?: BedrockAuth, 
/**
 * AWS named profile for [`BedrockAuth::Profile`] (reads `~/.aws/config`).
 */
awsProfile?: string, 
/**
 * AWS access key id for [`BedrockAuth::IamKeys`]. A non-secret identifier; the
 * paired secret access key and session token live in the keychain, never here.
 */
accessKeyId?: string, };
