// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";
import type { ReasoningEffort } from "./ReasoningEffort";
import type { ReasoningVisibility } from "./ReasoningVisibility";

/**
 * Non-secret, persisted LLM provider settings. Serialized as JSON to the app
 * config dir and round-tripped across IPC to drive the settings panel.
 */
export type ProviderConfig = { kind: ProviderKind, 
/**
 * Endpoint override. `None` = use [`ProviderKind::default_base_url`].
 */
baseUrl?: string, 
/**
 * Model id sent on each chat request.
 */
model: string, 
/**
 * Whether an API key is stored for this provider (OS keychain). Always
 * `false` in Phase 1 — the field keeps the contract stable for when hosted
 * providers and secrets land.
 */
hasKey: boolean, 
/**
 * When true, request and surface model reasoning/thinking streams (#181).
 */
thinking: boolean, 
/**
 * Reasoning *depth* dial (#395). Only bites when `thinking` is on; picks the
 * per-backend reasoning token budget in the host's `build_provider`. Mirrors
 * [`ProviderConnection::reasoning_effort`]. `#[serde(default)]` keeps legacy
 * `provider.json` files (and the CLI's) loading as [`ReasoningEffort::Medium`].
 */
reasoningEffort: ReasoningEffort, 
/**
 * Which loop steps request reasoning (#549). Only bites when `thinking` is
 * on. `#[serde(default)]` keeps legacy `provider.json` files loading as
 * [`ReasoningVisibility::All`] (the natural final answer shows a Thought).
 */
reasoningVisibility: ReasoningVisibility, };
