// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderConnection } from "./ProviderConnection";

/**
 * The full set of configured connections plus a pointer to the active one.
 * Replaces the single [`ProviderConfig`] as the persisted provider contract;
 * switching providers is now non-destructive.
 */
export type ProviderRegistry = { connections: Array<ProviderConnection>, 
/**
 * Id of the connection [`build_provider`](crate) resolves against. Always
 * references one of `connections`.
 */
active: string, 
/**
 * Registry schema version, bumped when a persisted-shape migration must run
 * exactly once on load (see [`ProviderRegistry::migrate`]). `#[serde(default)]`
 * makes a pre-versioning `provider-registry.json` load as `0`, which triggers
 * the pending migrations. Backend-internal; the frontend ignores it.
 */
schemaVersion: number, };
