// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How widely model reasoning (chain-of-thought) is requested across a turn's
 * loop steps (#549). Orthogonal to the on/off gate (`ChatRequest::thinking` /
 * `ProviderConfig::thinking`) and to the *depth* dial ([`ReasoningEffort`]):
 * this controls *which steps* request reasoning, not whether reasoning is on or
 * how long it runs.
 *
 * Background: a turn cannot know a-priori whether the current loop step will
 * dispatch more tools or emit the final answer (the model decides by returning
 * tool calls). So requesting reasoning only on a "final answer" step is not
 * expressible without requesting it on every step. The two honest points on
 * that tradeoff are:
 * - [`WrapUp`](Self::WrapUp): planning (first step) + the cap-forced wrap-up
 *   step only -- the latency-optimized choice (#449). A turn that finishes
 *   naturally before the cap answers with reasoning off, so its final answer
 *   shows no Thought block.
 * - [`All`](Self::All): every step. A short turn's natural final answer now
 *   carries reasoning. The persisted reasoning is always the *final* step's
 *   (the whole turn shares one assistant message id, and each step overwrites
 *   the row), so `All` does not bloat storage with mid-loop chains -- it only
 *   trades mid-loop reasoning latency for final-answer visibility.
 */
export type ReasoningVisibility = "wrapUp" | "all";
