// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-facing reasoning *depth* dial (#394/#395), mirroring the frontend
 * `Effort` (apps/desktop/src/store/model-config.ts: `low | medium | high`,
 * default `medium`). Orthogonal to the on/off gate (`ChatRequest::thinking`):
 * effort only matters when thinking is on, where it picks the reasoning token
 * budget every supported backend honors -- the SiliconFlow gateway
 * (`thinking_budget`, verified #394 across GLM-5.2 / Kimi-K2.7 / DeepSeek-V4-Pro),
 * Bedrock Converse and native Anthropic extended thinking (`budget_tokens`).
 *
 * Lives in `ff-core` (not `ff-llm`) so it can be both a field on the
 * [`ProviderConnection`] settings contract (exported to TS) and consumed by the
 * providers in `ff-llm`, which re-export it -- `ff-llm` depends on `ff-core`, so
 * the type cannot live the other way round without a dependency cycle (#395).
 */
export type ReasoningEffort = "low" | "medium" | "high";
