// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reasoning/thinking stream delta for an in-flight assistant message (#181).
 * Emitted only when the provider sends reasoning content; never persisted on
 * [`crate::Message`] — the frontend accumulates it separately from `content`.
 */
export type ReasoningEvent = { sessionId: string, messageId: string, delta: string, };
