// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A transient transport drop before any token; the turn is auto-retrying (#928).
 * The frontend renders "Reconnecting... {attempt}/{max_attempts}" on the in-progress
 * turn and clears it on the next `TokenEvent`/`TurnDoneEvent`. `attempt` is the
 * upcoming retry (1-based).
 */
export type ReconnectingEvent = { sessionId: string, messageId: string, attempt: number, maxAttempts: number, };
