// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A *resolved* model selection plus the capabilities derived from it (RFC 0005
 * §11.3). `connection` + `model` are the resolved pair (after the session,
 * phenotype, then global precedence); `supports_vision` and `supports_documents`
 * are derived from the resolved `(kind, model)` via [`model_supports_vision`] and
 * [`model_supports_documents`], never stored on a connection. This single-sources
 * attachment capability at the resolution point so a per-session model override is
 * gated by the model it actually runs, not the connection's default model.
 */
export type ResolvedModel = { connection: string, model: string, supportsVision: boolean, supportsDocuments: boolean, };
