// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextWindowSource } from "./ContextWindowSource";

/**
 * A *resolved* model selection plus the capabilities derived from it (RFC 0005
 * §11.3). `connection` + `model` are the resolved pair (after the session,
 * phenotype, then global precedence); `supports_vision` and `supports_documents`
 * are derived from the resolved `(kind, model)` via [`model_supports_vision`] and
 * [`model_supports_documents`], never stored on a connection. This single-sources
 * attachment capability at the resolution point so a per-session model override is
 * gated by the model it actually runs, not the connection's default model.
 */
export type ResolvedModel = { connection: string, model: string, supportsVision: boolean, supportsDocuments: boolean, 
/**
 * Effective served context window in tokens (#602): the window the runtime
 * will actually serve, not the model's trained maximum. `None` for non-Ollama
 * connections and when no probe ran. This is the denominator the compaction
 * budget is sized from; #598 must forward this same number. Stored as `u32`
 * (windows are tiny relative to the range) so the binding is `number`, not the
 * `bigint` ts-rs emits for `u64`, matching the FE `ServedWindow.window`.
 */
contextWindow: number | null, 
/**
 * Trained context ceiling (`/api/show` `context_length`), or `None` when
 * unknown. The "trained X" half of the chip readout.
 */
trainedContextWindow: number | null, 
/**
 * Which input produced [`context_window`](Self::context_window) (#602), or
 * `None` when no served window is known.
 */
contextWindowSource: ContextWindowSource | null, };
