// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunStatus } from "./RunStatus";

/**
 * A record of one fire, backing the ↗ open-session affordance and the audit
 * trail (#544 surfaces it; the type + store land here).
 */
export type RunRecord = { id: number, taskId: string, sessionId?: string, firedMs: number, status: RunStatus, };
