// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal status of one fire (RFC 0017 §8.4). A tool denial is incidental
 * within an otherwise-`Ok` run, not a terminal status.
 */
export type RunStatus = "ok" | "error" | "cancelled";
