// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much trust a given tool invocation needs. The agent loop auto-runs
 * [`Safety::ReadOnly`] and defers higher tiers to the [`PermissionMatrix`].
 *
 * Part of the IPC/settings surface (the Control-panel matrix, #702), exported to
 * TypeScript via `ts-rs`.
 */
export type Safety = "readonly" | "write" | "sensitive" | "dangerous";
