// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The most a headless scheduled fire may do without a human present (RFC 0017
 * §3). Enforced by the runner's `ScheduledApprover` (#542); `Dangerous` tool
 * calls are always denied headless regardless of this ceiling.
 */
export type SafetyCeiling = "read_only" | "write";
