// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SafetyCeiling } from "./SafetyCeiling";
import type { TaskKind } from "./TaskKind";

/**
 * A cron-scheduled agent task as presented in Settings → Scheduled (RFC 0017).
 * `cadenceLabel` and `nextRun` are derived from `cron` on read and never
 * persisted, so they cannot drift from the stored expression.
 */
export type ScheduledTask = { id: string, name: string, 
/**
 * The raw cron expression (6-field `sec min hour dom mon dow`, the form the
 * `cron` crate parses). Derived labels come from this.
 */
cron: string, kind: TaskKind, 
/**
 * Working directory the fire's session runs in; `None` inherits the global
 * default workspace.
 */
workspace?: string, 
/**
 * Phenotype/profile the fire runs as; `None` inherits the global active one.
 */
profile?: string, safetyCeiling: SafetyCeiling, paused: boolean, 
/**
 * Human cadence summary derived from `cron` (e.g. "Daily at 5:00 PM").
 * Server-computed on read; never stored.
 */
cadenceLabel: string, 
/**
 * Next fire time as epoch ms, computed from `cron` on read. `None` when the
 * expression has no future occurrence. Display-only — NOT the fire trigger.
 */
nextRun?: number, 
/**
 * Last fire time as epoch ms; `None` until the task has fired.
 */
lastRun?: number, };
