// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchBackend } from "./SearchBackend";

/**
 * Non-secret, persisted web-search settings. Serialized as JSON to the app config
 * dir and round-tripped across IPC to drive the settings panel.
 */
export type SearchConfig = { backend: SearchBackend, 
/**
 * Endpoint base URL. Required for SearXNG (e.g. `https://searx.example.org`);
 * the path `/search?format=json` is appended by the tool. Unused for Tavily.
 */
baseUrl?: string, 
/**
 * User email sent to NCBI E-utilities for best-practice identification (#1021).
 * Optional — anonymous when unset.
 */
email?: string, 
/**
 * Whether an API key is stored for this backend (OS keychain). Derived from
 * keychain presence by the host getter on every read (#1010) — never authoritative
 * on disk, so `skip_deserializing` drops any persisted value and the getter
 * recomputes it. Still serialized (disk + IPC) so the FE reads the live flag.
 */
hasKey: boolean, };
