// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchBackend } from "./SearchBackend";

/**
 * Non-secret, persisted web-search settings. Serialized as JSON to the app config
 * dir and round-tripped across IPC to drive the (future) settings panel.
 */
export type SearchConfig = { backend: SearchBackend, 
/**
 * Endpoint base URL. Required for SearXNG (e.g. `https://searx.example.org`);
 * the path `/search?format=json` is appended by the tool.
 */
baseUrl?: string, 
/**
 * Whether an API key is stored for this backend (OS keychain). Always `false`
 * for now — the field keeps the contract stable for when secrets land.
 */
hasKey: boolean, };
