// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which web-search provider `web_search` queries.
 */
export type SearchBackend = "searxNg" | "brave" | "openAiCompatible";
