// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchBackend } from "./SearchBackend";

/**
 * Whether an API key is stored (OS keychain) for one search backend (#1015). The
 * Settings key panel lists all backends; `present` is boolean-only — the secret
 * value never crosses this contract.
 */
export type SearchSecretPresence = { backend: SearchBackend, present: boolean, };
