// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A full-text search hit returned by [`SessionStore::search_messages`] and
 * [`SessionStore::search_in_session`] (#679). This is an IPC return type, so
 * its TypeScript binding is emitted to the desktop `bindings/` dir; the
 * `#[serde(rename_all)]` drives the camelCase field casing (ts-rs serde-compat
 * carries it into the binding), matching the ff-core convention.
 */
export type SearchHit = { sessionId: string, sessionTitle: string | null, messageId: string, role: string, snippet: string, 
/**
 * Unix epoch milliseconds. `#[ts(type = "number")]` matches the `Message`
 * / `Session` convention so the binding is `number`, not ts-rs's default
 * `bigint` for `i64` — the documented FE contract is `createdAt: number`.
 */
createdAt: number, };
