// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A piece of secret material stored in the OS keychain for a connection. Used as
 * the discriminator on the write-only `set_provider_secret` / `clear_provider_secret`
 * commands; the value itself is never part of any contract or command response.
 */
export type SecretKind = "apiKey" | "secretAccessKey" | "sessionToken";
