// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfluenceSource } from "./ConfluenceSource";
import type { McpServerConfig } from "./McpServerConfig";
import type { Mode } from "./Mode";
import type { ModelSelection } from "./ModelSelection";
import type { SessionStatus } from "./SessionStatus";

export type Session = { id: string, 
/**
 * The stated intention for this session (Intention-Aware Sessions principle).
 */
goal: string | null, 
/**
 * Human-facing display label, server-truth. Auto-derived from the first user
 * message (see [`auto_title`]) and overridable via the `rename_session` ipc.
 */
title: string | null, 
/**
 * Reserved for a future LLM-generated session summary. Unwired today; the
 * field exists so adding summaries later is not another contract migration.
 */
summary: string | null, status: SessionStatus, 
/**
 * Unix epoch milliseconds.
 */
createdAt: number, 
/**
 * Unix epoch milliseconds.
 */
updatedAt: number, 
/**
 * The phenotype this session runs as (#246). The *name* of a phenotype
 * (`default` or a file stem under `~/.flowforge/phenos/`), resolved per
 * turn to its persona / skills / model. `None` means "inherit the global
 * active phenotype" — so two panes can run different phenotypes while
 * untouched sessions always track the last-used global choice.
 */
phenotype?: string, 
/**
 * The agent autonomy mode this session runs as (RFC 0011 P2, #265). `None`
 * means "inherit the global `defaultMode` preference" — so a new session tracks
 * the user's default while a pane can override it independently (#148).
 */
mode?: Mode, 
/**
 * The working directory this session's tools run in (#200, #279). An absolute,
 * symlink-resolved path; `None` means "inherit the global default workspace".
 * Persisted in the session row so a chosen cwd survives a restart (RFC 0012 P4).
 */
workspace?: string, 
/**
 * The model this session runs on (RFC 0005 §11 Phase D, #499). A resolved
 * `(connection, model)` pair that overrides the phenotype's model for this
 * session only; `None` means "inherit the phenotype's model, falling back to
 * the global active selection" -- so a pane can pin its own model while
 * untouched sessions follow their phenotype.
 */
model?: ModelSelection, 
/**
 * Session-tier MCP server overrides (RFC 0018 section 3.1, top tier). Whole-record
 * overlay-by-id over the phenotype and global tiers (RFC section 11.5); `None`
 * means "inherit the phenotype + global resolution" -- so a pane can pin its own
 * MCP set while untouched sessions follow their phenotype. Persisted as JSON,
 * exactly like [`model`](Self::model).
 */
mcpServers?: Array<McpServerConfig>, 
/**
 * The session this one was forked from (#1074, RFC 0023 §4). `None` means
 * "lineage root" -- either never forked, or forked before lineage was
 * recorded (pre-existing history cannot be back-filled). Cleared to `None`
 * if the parent is deleted, so a fork outlives its source.
 */
parentSessionId?: string, 
/**
 * The last parent `seq` this session's transcript copied at fork time
 * (#1074). Because forking preserves `seq` verbatim, this is a coordinate
 * valid in *both* sessions: `seq <= fork_point_seq` is the shared prefix,
 * `seq > fork_point_seq` is post-fork divergence on either side.
 *
 * Two distinct `None` cases, told apart by [`parent_session_id`](Self::parent_session_id):
 * with no parent it means "lineage root"; with a parent it means the parent
 * was empty at fork time, i.e. an empty shared prefix.
 *
 * An **upper bound**, not a density guarantee: editing a message truncates
 * later ones without renumbering, so a `seq` at or below this point may no
 * longer exist on one side. Readers must intersect on actual rows.
 */
forkPointSeq?: number, 
/**
 * Provenance for a session produced by confluence (#1229, RFC 0023 §4/§5):
 * the source sessions whose transcripts were concatenated, in the order
 * they were appended, each with how many messages it contributed. `None`
 * for every ordinary session. Because segments are appended whole and never
 * interleaved, these counts partition this session's transcript into
 * contiguous spans, so any message maps back to its origin session by
 * position — structured provenance, never `<session_id>` tags in content.
 */
confluenceSources?: Array<ConfluenceSource>, };
