// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session's title was regenerated as an LLM one-line summary after its first
 * turn (#671 item 2b). The heuristic `auto_title` seeds an instant title on the
 * first user message; this replaces it with a better summary once a reply exists.
 * The frontend patches the cached session title in place -- no refetch.
 */
export type SessionTitleUpdatedEvent = { sessionId: string, title: string, };
