// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mode } from "./Mode";
import type { ModelSelection } from "./ModelSelection";
import type { SessionStatus } from "./SessionStatus";

export type Session = { id: string, 
/**
 * The stated intention for this session (Intention-Aware Sessions principle).
 */
goal: string | null, 
/**
 * Human-facing display label, server-truth. Auto-derived from the first user
 * message (see [`auto_title`]) and overridable via the `rename_session` ipc.
 */
title: string | null, 
/**
 * Reserved for a future LLM-generated session summary. Unwired today; the
 * field exists so adding summaries later is not another contract migration.
 */
summary: string | null, status: SessionStatus, 
/**
 * Unix epoch milliseconds.
 */
createdAt: number, 
/**
 * Unix epoch milliseconds.
 */
updatedAt: number, 
/**
 * The phenotype this session runs as (#246). The *name* of a phenotype
 * (`default` or a file stem under `~/.flowforge/phenos/`), resolved per
 * turn to its persona / skills / model. `None` means "inherit the global
 * active phenotype" — so two panes can run different phenotypes while
 * untouched sessions always track the last-used global choice.
 */
phenotype?: string, 
/**
 * The agent autonomy mode this session runs as (RFC 0011 P2, #265). `None`
 * means "inherit the global `defaultMode` preference" — so a new session tracks
 * the user's default while a pane can override it independently (#148).
 */
mode?: Mode, 
/**
 * The working directory this session's tools run in (#200, #279). An absolute,
 * symlink-resolved path; `None` means "inherit the global default workspace".
 * Persisted in the session row so a chosen cwd survives a restart (RFC 0012 P4).
 */
workspace?: string, 
/**
 * The model this session runs on (RFC 0005 §11 Phase D, #499). A resolved
 * `(connection, model)` pair that overrides the phenotype's model for this
 * session only; `None` means "inherit the phenotype's model, falling back to
 * the global active selection" -- so a pane can pin its own model while
 * untouched sessions follow their phenotype.
 */
model?: ModelSelection, };
