// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session's working directory as surfaced to the frontend selector (#200,
 * #211). `path` is the absolute, symlink-resolved cwd; `git_branch` is the
 * repo's current branch when the cwd is a git working tree (`None` otherwise,
 * e.g. not a repo or detached HEAD), so the selector can render `repo - branch`.
 */
export type SessionWorkspace = { path: string, gitBranch: string | null, };
