// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `SKILL.md` frontmatter. Collection fields default to empty so a minimal
 * manifest (just `name` + `description` + `version`) deserializes cleanly.
 */
export type SkillManifest = { name: string, description: string, version: string, author?: string, 
/**
 * Tool names that must resolve in the `ToolRegistry` when the skill loads.
 */
tools: Array<string>, 
/**
 * MCP server ids — declared in M3, enforced in M4.
 */
mcp: Array<string>, 
/**
 * Search/discovery keywords.
 */
keywords: Array<string>, };
