// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvolveCostEstimate } from "./EvolveCostEstimate";

/**
 * Backend -> frontend request to approve an optimize/evolve rewrite of a skill
 * (M3.5, RFC 0001 §8). The model has proposed `after_body`; the frontend shows the
 * before→after diff (it has both bodies) plus the cost estimate, and the user
 * approves or rejects. Like a skill install, this is a standalone approval with no
 * turn, so it is keyed by `request_id` and answered via the shared
 * `respond_approval(request_id, request_id, approved)` command. On approval the
 * skill is version-bumped to `new_version`, retaining the previous version for
 * rollback — it is never silently overwritten.
 */
export type SkillEvolveApprovalRequestEvent = { requestId: string, skill: string, currentVersion: string, newVersion: string, beforeBody: string, afterBody: string, costEstimate: EvolveCostEstimate, };
