// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend -> frontend notice that the active skill set changed (an
 * activate/deactivate, or an install/uninstall reload that pruned a missing
 * skill). Carries the full active set so the frontend replaces its state rather
 * than diffing. The installed-skill list itself is re-fetched via `list_skills`.
 */
export type SkillsChangedEvent = { active: Array<string>, };
