// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillManifest } from "./SkillManifest";

/**
 * Backend -> frontend request to approve installing a skill (M3.2). Emitted after
 * the bundle is fetched and validated, so the user approves with the real declared
 * `manifest` (name, version, tools/permissions) in hand. The frontend replies via
 * the shared `respond_approval(request_id, approved)` command — the same gate used
 * for dangerous tool calls. `warnings` carries non-fatal validation notes.
 */
export type SkillInstallApprovalRequestEvent = { requestId: string, source: string, manifest: SkillManifest, warnings: Array<string>, };
