// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend -> frontend telemetry: a turn that had `skill` active finished (M3.5, RFC
 * 0001 §8). Emitted once per active skill when the turn ends. `tokens` is a coarse
 * cost proxy (streamed assistant characters / 4) until real provider usage is wired
 * (deferred with the M4 autonomous trigger); `turns` counts agent loop iterations;
 * `latency_ms` is wall-clock turn duration; `success` is true when the turn ended
 * cleanly (not error/cancel). `ff-signals` folds these into rolling per-skill
 * aggregates (mean tokens/turns, success rate).
 */
export type SkillCompleted = { skill: string, sessionId: string, tokens: number, latencyMs: number, turns: number, success: boolean, };
