// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend -> frontend telemetry: a skill became active for a turn (M3.5, RFC 0001
 * §8). Emitted once per active skill at the start of each agent turn. `ff-signals`
 * folds these into per-skill aggregates (activation counts); the frontend may also
 * surface live activity. Pairs with [`SkillCompleted`] at turn end.
 */
export type SkillActivated = { skill: string, sessionId: string, };
