// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A skill as presented to the frontend: discovery metadata plus whether it is
 * currently active. One DTO backs both `list_skills` (unranked, `score` = 0) and
 * `search_skills` (ranked). Distinct from [`SkillManifest`] (frontmatter only) —
 * it folds in runtime `active` state and a search `score`, and omits the
 * FE-irrelevant `tools`/`mcp`/`author` fields.
 */
export type SkillInfo = { name: string, description: string, version: string, keywords: Array<string>, 
/**
 * Whether the skill is in the global active set (its body is injected into
 * the system prompt for the next turn).
 */
active: boolean, 
/**
 * Lexical relevance from `search_skills`; `0` for the unranked `list_skills`.
 */
score: number, };
