// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rolling telemetry for one skill (RFC 0001 §8). Counts are cumulative; the means
 * are maintained incrementally (Welford-style running mean) so the store never
 * holds an unbounded sum. `successRate` is `successes / completions`. Means are
 * `0.0` until the first completion.
 */
export type SkillAggregate = { skill: string, 
/**
 * Times the skill was active at the start of a turn.
 */
activations: number, 
/**
 * Turns that finished with the skill active (the denominator for the means).
 */
completions: number, 
/**
 * Of `completions`, how many ended cleanly (not error/cancel).
 */
successes: number, 
/**
 * Rolling mean of the per-turn token cost proxy.
 */
meanTokens: number, 
/**
 * Rolling mean of agent loop iterations per turn.
 */
meanTurns: number, 
/**
 * Rolling mean of wall-clock turn latency, in milliseconds.
 */
meanLatencyMs: number, 
/**
 * `successes / completions`, or `0.0` before the first completion.
 */
successRate: number, };
