// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress state of a single ledger step (#74).
 */
export type StepStatus = "pending" | "active" | "blocked" | "done";
