// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a turn ended without a usable answer (#658). The single source of truth
 * for the `[stopped…]` marker text the agent loop persists, so the frontend can
 * classify and render a stopped turn structurally instead of string-matching the
 * marker. Persisted on the assistant [`Message`] and carried on
 * [`TurnDoneEvent`](crate::events::TurnDoneEvent); absent for a normal turn.
 */
export type StopReason = "cancelled" | "toolLimit" | "stall" | "emptyResponse" | "interrupted";
