// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A curated-memory stratum (RFC 0008 §4) — the editable sections of `MEMORY.md`.
 * Wire contract for the Settings → Memory editor (#868/#969); mirrors the ff-memory
 * domain `Stratum`, kept separate so the wire type owns its own derives (same
 * pattern as [`MemoryFileKind`]). The host maps this to the domain enum.
 */
export type Stratum = "identity" | "patterns" | "focus";
