// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuiltinAction } from "./BuiltinAction";

/**
 * What a fire does. A sum type so the illegal state "a built-in with a
 * free-text prompt" is unrepresentable (RFC 0017 §5).
 */
export type TaskKind = { "kind": "prompt", "value": string } | { "kind": "builtin", "value": BuiltinAction };
