// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend -> frontend request to put a clarifying question to the user (the
 * `ask_user` tool, #44). The turn pauses until the frontend replies via the
 * `respond_ask(session_id, call_id, answer)` command. Dismissing it (turn cancel)
 * resolves the question as "[no answer: question dismissed]" — never a hang. `call_id` correlates with
 * the [`ToolCallEvent`] / [`ToolResultEvent`] for the same step.
 */
export type ToolAskRequestEvent = { sessionId: string, messageId: string, callId: string, question: string, };
