// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputStreamKind } from "./OutputStreamKind";

/**
 * A live chunk of a running command's output (#680), emitted as the process
 * produces it — before (and in addition to) the final [`ToolResultEvent`]. The
 * frontend appends `delta` to the running tool-call block so long builds/tests
 * show progress instead of appearing frozen. `call_id` correlates with the
 * [`ToolCallEvent`] / [`ToolResultEvent`] for the same step.
 */
export type ToolOutputChunkEvent = { sessionId: string, messageId: string, callId: string, stream: OutputStreamKind, delta: string, };
