// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolCallEvent = { sessionId: string, 
/**
 * Assistant message the call belongs to.
 */
messageId: string, 
/**
 * Correlates the call with its [`ToolResultEvent`].
 */
callId: string, tool: string, args: unknown, };
