// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalSafety } from "./ApprovalSafety";
import type { ProposePrScope } from "./ProposePrScope";

export type ToolApprovalRequestEvent = { sessionId: string, 
/**
 * Assistant message the call belongs to.
 */
messageId: string, 
/**
 * Correlates with the [`ToolCallEvent`] / [`ToolResultEvent`] for this call.
 */
callId: string, tool: string, args: unknown, 
/**
 * Trust level — read-only calls never require approval.
 */
safety: ApprovalSafety, 
/**
 * Scope-at-a-glance for a `propose_pr` gate (#1252): the files/lines about to
 * be pushed, computed by the host at approval-emit time. `None` for every
 * other tool, and best-effort — a git failure yields `None` rather than
 * blocking the gate. The line-level review still happens on the draft PR;
 * this is only so the human sees *what's about to be pushed* without leaving
 * the window.
 */
scopeSummary?: ProposePrScope, };
