// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolApprovalRequestEvent = { sessionId: string, 
/**
 * Assistant message the call belongs to.
 */
messageId: string, 
/**
 * Correlates with the [`ToolCallEvent`] / [`ToolResultEvent`] for this call.
 */
callId: string, tool: string, args: unknown, 
/**
 * `"write"` or `"dangerous"` — read-only calls never require approval.
 */
safety: string, };
