// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-turn timing baseline (F1, #427): the wall-clock breakdown the performance
 * epic (#426) measures every later change against. `round_trips` is the number of
 * provider responses (agent loop iterations) this turn; `iter_ms` is the
 * per-iteration wall-clock in arrival order; `flushes` counts silent mid-turn
 * memory flushes (each an extra provider round-trip); `output_tokens` is the
 * estimated assistant output tokens (tokenx-rs); `prefill_estimates` is the per-
 * round-trip projected request size and `tier1_fires`/`tier2_fires` count how
 * often each compaction tier engaged (F1b, #441). The F1b fields are optional on
 * the wire -- the desktop always populates them, but a non-desktop emitter may
 * omit them cleanly (#475 follow-up). Emitted once at turn end.
 */
export type TurnStatsEvent = { sessionId: string, roundTrips: number, totalMs: number, iterMs: Array<number>, flushes: number, outputTokens: number, 
/**
 * F1b (#441): projected prefill-token estimate of each round-trip's outgoing
 * request (post-compaction wire), in iteration order. Omitted by emitters that
 * do not compute F1b telemetry.
 *
 * Invariant when present: `prefill_estimates.len() == round_trips` (one
 * estimate per round-trip). The frontend should assert this when it eventually
 * consumes `turn:stats` events.
 */
prefillEstimates?: Array<number>, 
/**
 * F1b (#441): iterations that engaged the Tier-1 extractive compaction pass.
 * Omitted by emitters that do not compute F1b telemetry.
 */
tier1Fires?: number, 
/**
 * F1b (#441): iterations that engaged the Tier-2 abstractive cold-tail summary.
 * Omitted by emitters that do not compute F1b telemetry.
 */
tier2Fires?: number, 
/**
 * TTFT: milliseconds from the moment the host handed the request to
 * `run_turn` to the arrival of the first assistant token. Answers the
 * dominant question the #427 baseline could not: "how long until the
 * model starts talking?" — the sum of provider RTT + queue + prefill.
 * `None` when the turn produced no assistant message (e.g. an early
 * error or cancel before the first token streamed).
 */
firstTokenMs?: number, };
