// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-turn timing baseline (F1, #427): the wall-clock breakdown the performance
 * epic (#426) measures every later change against. `round_trips` is the number of
 * provider responses (agent loop iterations) this turn; `iter_ms` is the
 * per-iteration wall-clock in arrival order; `flushes` counts silent mid-turn
 * memory flushes (each an extra provider round-trip); `chars` is the streamed
 * assistant text, a coarse token-cost proxy. Emitted once at turn end.
 */
export type TurnStatsEvent = { sessionId: string, roundTrips: number, totalMs: number, iterMs: Array<number>, flushes: number, chars: number, };
