// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnDoneEvent = { sessionId: string, messageId: string, 
/**
 * Estimated token count of the session context at turn end, for a
 * frontend context-usage indicator. `None` when not assessed.
 */
tokenCount: number | null, };
