// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StopReason } from "./StopReason";

export type TurnDoneEvent = { sessionId: string, messageId: string, 
/**
 * Estimated token count of the session context at turn end, for a
 * frontend context-usage indicator. `None` when not assessed.
 */
tokenCount: number | null, 
/**
 * Why the turn stopped without a usable answer (#658), when it did. `None`
 * for a normal completion. Lets the frontend offer the Continue affordance
 * and render the Cancelled banner without string-matching the notice text.
 */
stopReason: StopReason | null, };
