// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextBreakdown } from "./ContextBreakdown";
import type { StopReason } from "./StopReason";
import type { TurnUsage } from "./TurnUsage";

export type TurnDoneEvent = { sessionId: string, messageId: string, 
/**
 * Estimated token count of the session context at turn end, for a
 * frontend context-usage indicator. `None` when not assessed.
 */
tokenCount: number | null, 
/**
 * Why the turn stopped without a usable answer (#658), when it did. `None`
 * for a normal completion. Lets the frontend offer the Continue affordance
 * and render the Cancelled banner without string-matching the notice text.
 */
stopReason: StopReason | null, 
/**
 * Component breakdown of the context-size estimate (#931), for the
 * context-usage popover's segmented bar and rows. `None` when not assessed.
 */
breakdown?: ContextBreakdown, 
/**
 * Provider-reported token usage for this turn (#931). `None` when the
 * provider does not report usage (e.g. no metadata frame).
 */
usage?: TurnUsage, };
