// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-turn timing baseline (F1, #427): the wall-clock breakdown the performance
 * epic (#426) measures every later change against. `round_trips` is the number of
 * provider responses (agent loop iterations) this turn; `iter_ms` is the
 * per-iteration wall-clock in arrival order; `flushes` counts silent mid-turn
 * memory flushes (each an extra provider round-trip); `output_tokens` is the
 * estimated assistant output tokens (tokenx-rs); `prefill_estimates` is the per-
 * round-trip projected request size and `tier1_fires`/`tier2_fires` count how
 * often each compaction tier engaged (F1b, #441). The F1b fields are optional on
 * the wire -- the desktop always populates them, but a non-desktop emitter may
 * omit them cleanly (#475 follow-up). Emitted once at turn end.
 */
export type TurnStatsEvent = { sessionId: string, roundTrips: number, totalMs: number, iterMs: Array<number>, flushes: number, outputTokens: number, 
/**
 * F1b (#441): projected prefill-token estimate of each round-trip's outgoing
 * request (post-compaction wire), in iteration order. Omitted by emitters that
 * do not compute F1b telemetry.
 *
 * Invariant when present: `prefill_estimates.len() == round_trips` (one
 * estimate per round-trip). The frontend should assert this when it eventually
 * consumes `turn:stats` events.
 */
prefillEstimates?: Array<number>, 
/**
 * F1b (#441) / #1045: number of fold **ticks** this turn -- times the
 * layered Tier-1 pass advanced the frozen boundary. With the Near-budget
 * hysteresis (#1045) this is `<= 1` for most turns; it is NOT a
 * per-iteration "the pass ran" count. Omitted by emitters that do not
 * compute F1b telemetry.
 */
tier1Fires?: number, 
/**
 * F1b (#441): iterations that engaged the Tier-2 abstractive cold-tail summary.
 * Omitted by emitters that do not compute F1b telemetry.
 */
tier2Fires?: number, 
/**
 * #1045: `compaction_retrieve` calls the model made this turn -- the recall
 * cost of the layered fold. Omitted by emitters that do not compute it.
 */
retrieveCalls?: number, 
/**
 * TTFT (end-to-end): milliseconds from the moment the host handed the
 * request to `run_turn` to the arrival of the first assistant token.
 * Anchored at `turn_start`, so it *includes* any pre-first-token work the
 * turn did before the model spoke — most notably a context-pressure memory
 * flush (a full extra provider round-trip) and planning-step reasoning.
 * Pair it with [`Self::prompt_latency_ms`] to separate prefill from that
 * side work. `None` when the turn produced no assistant message (e.g. an
 * early error or cancel before the first token streamed).
 */
firstTokenMs?: number, 
/**
 * #960: pure provider prefill latency of round-trip 0, in milliseconds —
 * measured inside `run_turn` from the instant the provider stream is
 * returned to the first output-carrying chunk. Unlike
 * [`Self::first_token_ms`], it excludes the pre-first-token memory flush and
 * the `turn_start`→stream-start gap, so it isolates the cache-addressable
 * prefill cost. `promptLatencyMs / firstTokenMs` is the "prefill share": a
 * value near 100% means the wait was almost all prefill; a small value means
 * it was dominated by flush/reasoning side work. `None` when the turn
 * produced no token, or for emitters that do not compute it.
 */
promptLatencyMs?: number, 
/**
 * #971: wall-clock (ms) spent in the pre-main-call **Tier-2 abstractive
 * summarize** this turn (the uncached `summarize_cold` LLM call; the
 * cross-turn-cache reuse path is excluded). The dominant "other" latency on
 * an over-budget re-trigger turn. `None` when no summarize ran this turn.
 */
tier2Ms?: number, };
