// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider-reported token usage for a turn (#931), summed across the turn's
 * round-trips. Distinct from the `chars/4` proxy: these are authoritative
 * counts from the provider's usage metadata (Bedrock `ConverseStream`
 * `TokenUsage`, OpenAI `usage`). The frontend accumulates these across turns to
 * render the SESSION TOTALS block; all fields are 0 when the provider does not
 * report usage.
 */
export type TurnUsage = { 
/**
 * Prompt tokens sent to the model this turn (cumulative over round-trips).
 */
inputTokens: number, 
/**
 * Completion tokens generated by the model this turn.
 */
outputTokens: number, 
/**
 * Prompt-prefix cache-read (hit) tokens this turn.
 */
cacheReadTokens: number, 
/**
 * Prompt-prefix cache-write (miss) tokens this turn.
 */
cacheWriteTokens: number, };
