// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Download progress for an in-flight self-update install (#566, RFC 0014 section
 * 12.2). Emitted as `update:progress` from `install_update` per downloaded chunk;
 * `total` is the content length, absent when the feed does not send one (the UI
 * then renders an indeterminate bar). App-global -- there is one install at a time,
 * so no session id. A terminal `update:download-finished` event (empty payload)
 * follows the last chunk, before the app relaunches.
 */
export type UpdateProgressEvent = { downloaded: bigint, total: bigint | null, };
