// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of checking a step's claim against its evidence (#74). The
 * explicit `Unverifiable` value is the point of the ledger: a step that could
 * not be checked is recorded as such, never quietly treated as done.
 */
export type Verdict = "match" | "drift" | "unverifiable";
