#!/usr/bin/env bash
# Generate the crate dependency graph for ARCHITECTURE.md from cargo metadata.
#
# Single source of truth for the "Dependency direction" section: never hand-edit
# that block. Run `scripts/gen-arch-graph.sh` to print it, or
# `scripts/gen-arch-graph.sh --check` to verify ARCHITECTURE.md is in sync (CI).
#
# The graph is derived from each crate's declared `ff-*` dependencies (workspace
# members only, normal deps — dev/build deps excluded), so it cannot drift from
# the real Cargo.toml wiring the way a hand-written diagram would.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARCH_FILE="$ROOT/ARCHITECTURE.md"
BEGIN_MARK="<!-- BEGIN GENERATED DEP GRAPH -->"
END_MARK="<!-- END GENERATED DEP GRAPH -->"

graph() {
  ( cd "$ROOT" && cargo metadata --format-version 1 --no-deps 2>/dev/null ) | python3 -c '
import json, sys
m = json.load(sys.stdin)
pkgs = {p["name"]: p for p in m["packages"]}
ff = {n for n in pkgs if n.startswith("ff-")}

def deps_of(name):
    return sorted(
        d["name"] for d in pkgs[name]["dependencies"]
        if d["name"] in ff and d.get("kind") in (None, "normal")
    )

print("```")
print("# crate  ->  its ff-* dependencies (workspace members, normal deps only)")
print("# Generated by scripts/gen-arch-graph.sh — do not edit by hand.")
print()
for n in sorted(ff):
    d = deps_of(n)
    rhs = chr(32).join(d) if d else "(no ff-* deps — leaf/root)"
    print(f"{n:20} -> {rhs}")
extra = sorted(
    n for n in pkgs
    if n not in ff and any(dep["name"] in ff for dep in pkgs[n]["dependencies"])
)
if extra:
    print()
    print("# apps / hosts:")
    for n in extra:
        d = sorted(dep["name"] for dep in pkgs[n]["dependencies"]
                   if dep["name"] in ff and dep.get("kind") in (None, "normal"))
        rhs = chr(32).join(d)
        print(f"{n:20} -> {rhs}")
print("```")
'
}

if [[ "${1:-}" == "--check" ]]; then
  tmp="$(mktemp)"
  {
    echo "$BEGIN_MARK"
    graph
    echo "$END_MARK"
  } > "$tmp"
  # Extract the current block from ARCHITECTURE.md
  cur="$(mktemp)"
  awk "/$BEGIN_MARK/{f=1} f{print} /$END_MARK/{f=0}" "$ARCH_FILE" > "$cur"
  if diff -u "$cur" "$tmp" >/dev/null; then
    echo "ARCHITECTURE.md dependency graph is in sync."
    rm -f "$tmp" "$cur"; exit 0
  else
    echo "ARCHITECTURE.md dependency graph is STALE. Regenerate with:" >&2
    echo "  scripts/gen-arch-graph.sh --write" >&2
    diff -u "$cur" "$tmp" >&2 || true
    rm -f "$tmp" "$cur"; exit 1
  fi
fi

if [[ "${1:-}" == "--write" ]]; then
  [[ -f "$ARCH_FILE" ]] || { echo "ARCHITECTURE.md not found" >&2; exit 1; }
  tmp="$(mktemp)"
  awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
    $0 ~ b {print; skip=1; system("scripts/gen-arch-graph.sh"); next}
    $0 ~ e {print; skip=0; next}
    !skip {print}
  ' "$ARCH_FILE" > "$tmp"
  mv "$tmp" "$ARCH_FILE"
  echo "Wrote generated graph into ARCHITECTURE.md"
  exit 0
fi

graph
